### ISSUE TITLE
Following up significant interactions in GLMM

### ISSUE THREAD

**Issue by OmidGhasemi21** [singmann/afex#100]
Hi Henrik,

I ran a GLMM and found several significant interactions including:

```
m17 <- mixed (pseudo_accuracy ~ conf*instruction* sub_type* general_ability + (conf+instruction|subj_id),
                          data, method = "LRT",
                          control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 1e6)),
                          expand_re = TRUE, family=binomial(link="logit"), cl = cl)

#             Effect            df     Chisq    p.value
# instruction:general_ability  1    6.14 *     .01
# conf:instruction             1    3.79 +     .05
```

To do follow-up tests, first, I subtracted probabilities that `emmeans()` created, but the differences between the two ability groups were similar under each instruction condition (for the first interaction). 

```
emmeans(m17, "general_ability", by= "instruction", type = "response")

#instruction = Logic:
# general_ability  prob      SE  df asymp.LCL asymp.UCL
# High Ability    0.988 0.00401 Inf     0.977     0.994
# Low Ability     0.911 0.02174 Inf     0.858     0.945

# instruction = Belief:
# general_ability  prob      SE  df asymp.LCL asymp.UCL
# High Ability    0.951 0.01057 Inf     0.926     0.968
# Low Ability     0.874 0.02251 Inf     0.823     0.912


> 0.988 - .911
# [1] 0.077
> .951 - 0.874
# [1] 0.077
```

The second method that I tried was using odd ratios as you used in your tutorial. I used the second interaction (conflict x instruction) here. The odd ratio resulted from the `pair()` is larger for the logic instruction condition, while, it is obvious that the difference between non-conflict and conflict is larger for the belief instruction condition.

```
update(pairs(emmeans(m17, "conf", by= "instruction", type = "response")), by = NULL, adjust = "holm")
# contrast                instruction odds.ratio   SE  df z.ratio p.value
# non_conflict / conflict Logic            10.65 2.81 Inf 8.972   <.0001 
# non_conflict / conflict Belief            6.95 1.61 Inf 8.375   <.0001 

afex_plot(m17, x = "instruction", trace = "conf")
```
<img width="500" alt="Screen Shot" src="https://user-images.githubusercontent.com/45413424/98747128-014d1080-240b-11eb-9045-68ca26188545.png">

So, here is my question. What is the best method to follow-up an interaction?
1. Using raw means? but sometimes raw means are similar for each condition whilst the interaction is significant.
2. Subtracting probabilities? but sometimes probabilities are similar for each condition whilst the interaction is significant.
3. using the odd ratios? Then how to interpret a bigger odd ratio when the plots suggest something else?

Sorry for my long question and thank you in advance for your help.

**Comment by mattansb** [comment]
(Just to note that there are actually 3 options. See this [blog post](https://shouldbewriting.netlify.app/posts/2020-04-13-estimating-and-testing-glms-with-emmeans/). Also a good read is [McCabe et al.](https://doi.org/10.31234/osf.io/th94c) about the different considerations for different methods.)

**Comment by OmidGhasemi21** [comment]
Thank you so much @mattansb for sharing these two super useful tutorials. So, what I understand from your blog post is that there is no "best method" in interpreting interactions in GLMs and each of the three methods can result in different conclusions. From McCabe's paper and also Mize's paper, I realized that interpreting interaction on the latent level (log) is not a good option. Moreover, the effect in the emmeans without `type= 'response'` is hard to interpret. So, we have two more options.

1. **Differences in probabilities**: This seems a good method, but as you can see in the first interaction effect of my model, the differences between probabilities of one factor (general ability) were similar for both levels of the second factor (instruction). Then, where is the interaction coming from?

2. **Ratios of probabilities**: My confusion with this method is also rises from the second interaction term. The plot strongly suggested that the effect of conflict is larger for the belief condition, but the odd ratio of this condition is actually smaller than the other condition (logic). Then how can I interpret odd ratio to get a consistent result with the figure?

Thank you.

**Comment by mattansb** [comment]
I think the take home message from both the blog post and McCabe's paper is to have the analysis be guided by your hypothesis - is your hypothesis concerned with the latent log-odds? Or the probability? Having said that:

1. The interaction effect in the ANOVA table is based on the log-odds scale. So it is possible that there is no difference of differences in the probabilities - thought that might be noteworthy to report as well.

2. Yeah, this is the problem with odds ratios (also risk ratios to some extent) - they don't behave as you would expect, especially near the edges (1 and 0). But the math holds true - though the differences are smaller, the ratio of odds ratios is larger:

``` r
p1_1 <- 0.99
p2_1 <- 0.95
p1_2 <- 0.88
p2_2 <- 0.82


(p1_1 / (1 - p1_1)) / (p2_1 / (1 - p2_1))
#> [1] 5.210526
(p1_2 / (1 - p1_2)) / (p2_2 / (1 - p2_2))
#> [1] 1.609756
```

**Comment by singmann** [comment]
I agree with everything from @mattansb and only want to add a substantive comment to the already excellent statistical advice. 

From what we see above, differences of differences (i.e., interactions) are a tricky issue for accuracy data. This has led to quite a few theoretical discussions in the reasoning literature (where this questions also seems to be situated). The most prominent example is the belief bias effect, where this interaction is typically observed on the levels of probabilities. The theoretically interesting question whether this also holds on the latent psychological scale where the judgment emerges. For this question to make sense, we need to have a cognitive model of how the judgment is created on the latent scale. The first such model is from Klauer and colleagues in a discrete-state model:

Klauer, K. C., Musch, J., & Naumer, B. (2000). On belief bias in syllogistic reasoning. Psychological Review, 107(4), 852–884. https://doi.org/10.1037//0033-295X.107.4.852

We have recently also addressed this and provide a rather extensive discussion of the question what does an interaction on the probability scale mean, especially in a signal-detection type framework (see section "Implicit linear-model assumptions and SDT-based criticism"):
Trippas, D., Kellen, D., Singmann, H., Pennycook, G., Koehler, D. J., Fugelsang, J. A., & Dubé, C. (2018). [Characterizing belief bias in syllogistic reasoning: A hierarchical Bayesian meta-analysis of ROC data](http://singmann.org/download/publications/Trippas-et-al.-2018-Characterizing-belief-bias-in-syllogistic-reasonin.pdf). Psychonomic Bulletin & Review, 25(6), 2141–2174. https://doi.org/10.3758/s13423-018-1460-7

I have the feeling there is not much more to say on this issue, so I would be inclined to close this issue. But then, I also do not want to stifle the conversation.

**Comment by OmidGhasemi21** [comment]
Thank you @singmann and @mattansb for your clarifications. I know realized that interpreting interaction from the model product (as was suggested by resources that Mattan recommended) is not the best method. And also our hypothesis determines on which level (i.e., latent level, probability response level, or ratio response level) we should interpret the interaction. For future readers, besides the resources that Mattan recommended, I suggest this paper as well:

Mize, T. D. (2019). Best practices for estimating, interpreting, and presenting nonlinear interaction effects. Sociological Science, 6, 81-117.

Henrik, my problem is solved and from my side, feel free to close the issue. Thank you again.
