### ISSUE TITLE
error for running mixed() with a null model (no fixed effect)

### ISSUE THREAD

**Issue by ShanReal** [singmann/afex#103]
Hi there,

Thanks for developing the package (Afex).

May I know what is the meaning for the following error? 
I was trying to compare a random intercept model with a null model (no fixed effect model) using mixed() (glmer), but it seemed that it cannot run for the null model:

> model1_null <- mixed(response ~ 1 + (1|subj), data = data_new, method = "LRT", family = binomial )
Contrasts set to contr.sum for the following variables: response, subj
Fitting 1 (g)lmer() models:
[.]
Error in UseMethod("logLik") : 
  no applicable method for 'logLik' applied to an object of class "NULL"
In addition: Warning message:
In max(effect.order) : no non-missing arguments to max; returning -Inf

> model1_null
Error: object 'model1_null' not found

However, if I used library(lme4) to run the null model, it worked:

> library(lme4)
> mod1_null <- glmer(response~ 1 +    (1 | subj), data = data_new, family = binomial(link = "logit"), control = glmerControl(optimizer = "bobyqa"),   nAGQ = 10)

> anova(mod1_intercept, test='LRT')
Analysis of Variance Table
                 Df  Sum Sq Mean Sq F value
greed             1 15.4638 15.4638 15.4638
fear              1  2.7912  2.7912  2.7912
group             2  0.8595  0.4298  0.4298
greed:fear        1  0.1378  0.1378  0.1378
greed:group       2  0.4749  0.2375  0.2375
fear:group        2  6.4799  3.2399  3.2399
greed:fear:group  2  6.1245  3.0623  3.0623

> anova(mod1_intercept,mod1_null)
Data: data_new
Models:
mod1_null: response ~ 1 + (1 | subj)
mod1_intercept: response ~ greed * fear * group + (1 | subj)
               Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)    
mod1_null       2 4357.4 4370.6 -2176.7   4353.4                             
mod1_intercept 13 4348.2 4433.4 -2161.1   4322.2 31.278     11  0.0009949 ***
---

How should I adjust the model in the mixed() so that I can use the mixed to run the null model and do model comparison?

**Comment by singmann** [comment]
The `mixed` function is for testing fixed effects automatically. So there is no need to specify the null model by hand, it is all part of the output of the full model when using `method = "LRT"`.

See here for a simple example:
``` r
suppressPackageStartupMessages(library("afex"))
data("Machines", package = "MEMSS") 
m1 <- mixed(score ~ Machine + (Machine|Worker), data=Machines, method = "LRT")
#> Contrasts set to contr.sum for the following variables: Machine, Worker
#> REML argument to lmer() set to FALSE for method = 'PB' or 'LRT'
#> Fitting 2 (g)lmer() models:
#> [..]

str(m1, 1)
#> List of 6
#>  $ anova_table      :Classes 'anova' and 'data.frame':   1 obs. of  4 variables:
#>   ..- attr(*, "heading")= chr [1:4] "Mixed Model Anova Table (Type 3 tests, LRT-method)\n" "Model: score ~ Machine + (Machine | Worker)" "Data: Machines" "Df full model: 10"
#>   ..- attr(*, "sig_symbols")= chr [1:4] " +" " *" " **" " ***"
#>  $ full_model       :Formal class 'lmerModLmerTest' [package "lmerTest"] with 17 slots
#>  $ restricted_models:List of 1
#>  $ tests            :List of 1
#>  $ data             :'data.frame':   54 obs. of  3 variables:
#>  $ call             : language mixed(formula = score ~ Machine + (Machine | Worker), data = Machines,      method = "LRT")
#>  - attr(*, "class")= chr "mixed"
#>  - attr(*, "type")= num 3
#>  - attr(*, "method")= chr "LRT"

## full model
m1$full_model
#> Linear mixed model fit by maximum likelihood  ['lmerModLmerTest']
#> Formula: score ~ Machine + (Machine | Worker)
#>    Data: data
#>       AIC       BIC    logLik  deviance  df.resid 
#>  236.4178  256.3077 -108.2089  216.4178        44 
#> Random effects:
#>  Groups   Name        Std.Dev. Corr       
#>  Worker   (Intercept) 4.7849              
#>           Machine1    2.3699   -0.65      
#>           Machine2    3.4115    0.84 -0.71
#>  Residual             0.9616              
#> Number of obs: 54, groups:  Worker, 6
#> Fixed Effects:
#> (Intercept)     Machine1     Machine2  
#>     59.6500      -7.2944       0.6722

## intercept only model
m1$restricted_models[[1]]
#> Linear mixed model fit by maximum likelihood  ['lmerModLmerTest']
#> Formula: score ~ 0 + m.matrix[, -2:-3] + (Machine | Worker)
#>    Data: data
#>       AIC       BIC    logLik  deviance  df.resid 
#>  249.5572  265.4691 -116.7786  233.5572        46 
#> Random effects:
#>  Groups   Name        Std.Dev. Corr       
#>  Worker   (Intercept) 5.2828              
#>           Machine1    7.6712   -0.58      
#>           Machine2    3.4770    0.83 -0.40
#>  Residual             0.9616              
#> Number of obs: 54, groups:  Worker, 6
#> Fixed Effects:
#> m.matrix[, -2:-3]  
#>             57.41

## mixed output
m1
#> Mixed Model Anova Table (Type 3 tests, LRT-method)
#> 
#> Model: score ~ Machine + (Machine | Worker)
#> Data: Machines
#> Df full model: 10
#>    Effect df     Chisq p.value
#> 1 Machine  2 17.14 ***   <.001
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1
## is equivalent to
anova(m1$full_model, m1$restricted_models[[1]])
#> Data: data
#> Models:
#> m1$restricted_models[[1]]: score ~ 0 + m.matrix[, -2:-3] + (Machine | Worker)
#> m1$full_model: score ~ Machine + (Machine | Worker)
#>                           npar    AIC    BIC  logLik deviance  Chisq Df
#> m1$restricted_models[[1]]    8 249.56 265.47 -116.78   233.56          
#> m1$full_model               10 236.42 256.31 -108.21   216.42 17.139  2
#>                           Pr(>Chisq)    
#> m1$restricted_models[[1]]               
#> m1$full_model              0.0001898 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

<sup>Created on 2021-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
