### ISSUE TITLE
Adding geoms to `afex_plot()`

### ISSUE THREAD

**Issue by shirdekel** [singmann/afex#106]
I'd like to use both `ggbeeswarm::geom_quasirandom` and `ggplot2::boxplot` to represent my data in the background of an `afex_plot` plot.

Is there a reason why I can't simply add the geom after the `afex_plot` call?

``` r
library(afex)
#> Loading required package: lme4
#> Loading required package: Matrix
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> ************
#> Welcome to afex. For support visit: http://afex.singmann.science/
#> - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
#> - Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
#> - 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
#> - NEWS: library('emmeans') now needs to be called explicitly!
#> - Get and set global package options with: afex_options()
#> - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
#> - For example analyses see: browseVignettes("afex")
#> ************
#> 
#> Attaching package: 'afex'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer
library(ggplot2)

data(md_12.1)
aw <- aov_ez("id", "rt", md_12.1, within = "noise")
#> Warning: More than one observation per cell, aggregating the data using mean
#> (i.e, fun_aggregate = mean)!

## Works as expected

afex_plot(aw,
  x = "noise",
  data_geom = ggbeeswarm::geom_quasirandom,
)
#> Warning: Panel(s) show within-subjects factors, but not within-subjects error bars.
#> For within-subjects error bars use: error = "within"
```

![](https://i.imgur.com/PhisXpI.png)

``` r
## Works as expected

afex_plot(aw,
  x = "noise",
  data_geom = geom_boxplot,
)
#> Warning: Panel(s) show within-subjects factors, but not within-subjects error bars.
#> For within-subjects error bars use: error = "within"
```

![](https://i.imgur.com/shk41S0.png)

``` r
## Works as expected

ggplot(md_12.1, aes(y = rt, x = noise)) +
  ggbeeswarm::geom_quasirandom() +
  geom_boxplot()
```

![](https://i.imgur.com/vWMmrgH.png)

``` r
## Does not work as expected

afex_plot(aw,
  x = "noise",
  data_geom = ggbeeswarm::geom_quasirandom,
) +
  geom_boxplot()
#> Warning: Panel(s) show within-subjects factors, but not within-subjects error bars.
#> For within-subjects error bars use: error = "within"
```

![](https://i.imgur.com/sMqtF6p.png)

<sup>Created on 2021-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  ctype    en_AU.UTF-8                 
#>  tz       Australia/Sydney            
#>  date     2021-06-24                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version     date       lib source                            
#>  abind          1.4-5       2016-07-21 [1] CRAN (R 4.0.0)                    
#>  afex         * 0.28-1      2021-01-12 [1] CRAN (R 4.0.2)                    
#>  assertthat     0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                    
#>  backports      1.2.1       2020-12-09 [1] CRAN (R 4.0.2)                    
#>  beeswarm       0.4.0       2021-06-01 [1] CRAN (R 4.0.2)                    
#>  boot           1.3-27      2021-02-12 [1] CRAN (R 4.0.2)                    
#>  car            3.0-10      2020-09-29 [1] CRAN (R 4.0.2)                    
#>  carData        3.0-4       2020-05-22 [1] CRAN (R 4.0.0)                    
#>  cellranger     1.1.0       2016-07-27 [1] CRAN (R 4.0.0)                    
#>  cli            2.5.0       2021-04-26 [1] CRAN (R 4.0.2)                    
#>  coda           0.19-4      2020-09-30 [1] CRAN (R 4.0.2)                    
#>  colorspace     2.0-1       2021-05-04 [1] CRAN (R 4.0.2)                    
#>  crayon         1.4.1       2021-02-08 [1] CRAN (R 4.0.2)                    
#>  curl           4.3.1       2021-04-30 [1] CRAN (R 4.0.2)                    
#>  data.table     1.14.0      2021-02-21 [1] CRAN (R 4.0.2)                    
#>  DBI            1.1.1       2021-01-15 [1] CRAN (R 4.0.2)                    
#>  digest         0.6.27      2020-10-24 [1] CRAN (R 4.0.2)                    
#>  dplyr          1.0.7.9000  2021-06-20 [1] Github (tidyverse/dplyr@a25657c)  
#>  ellipsis       0.3.2       2021-04-29 [1] CRAN (R 4.0.2)                    
#>  emmeans        1.5.4-09004 2021-03-11 [1] Github (rvlenth/emmeans@7815617)  
#>  estimability   1.3         2018-02-11 [1] CRAN (R 4.0.0)                    
#>  evaluate       0.14        2019-05-28 [1] CRAN (R 4.0.0)                    
#>  fansi          0.5.0       2021-05-25 [1] CRAN (R 4.0.2)                    
#>  farver         2.1.0       2021-02-28 [1] CRAN (R 4.0.2)                    
#>  fastmap        1.1.0       2021-01-25 [1] CRAN (R 4.0.2)                    
#>  forcats        0.5.1       2021-01-27 [1] CRAN (R 4.0.2)                    
#>  foreign        0.8-81      2020-12-22 [1] CRAN (R 4.0.2)                    
#>  fs             1.5.0       2020-07-31 [1] CRAN (R 4.0.2)                    
#>  generics       0.1.0       2020-10-31 [1] CRAN (R 4.0.2)                    
#>  ggbeeswarm     0.6.0       2017-08-07 [1] CRAN (R 4.0.2)                    
#>  ggplot2      * 3.3.4       2021-06-16 [1] CRAN (R 4.0.2)                    
#>  glue           1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                    
#>  gtable         0.3.0       2019-03-25 [1] CRAN (R 4.0.0)                    
#>  haven          2.4.1       2021-04-23 [1] CRAN (R 4.0.2)                    
#>  highr          0.9         2021-04-16 [1] CRAN (R 4.0.2)                    
#>  hms            1.1.0       2021-05-17 [1] CRAN (R 4.0.2)                    
#>  htmltools      0.5.1.9005  2021-06-20 [1] Github (rstudio/htmltools@7fbab16)
#>  httr           1.4.2       2020-07-20 [1] CRAN (R 4.0.2)                    
#>  knitr          1.33        2021-04-24 [1] CRAN (R 4.0.2)                    
#>  labeling       0.4.2       2020-10-20 [1] CRAN (R 4.0.2)                    
#>  lattice        0.20-41     2020-04-02 [1] CRAN (R 4.0.2)                    
#>  lifecycle      1.0.0       2021-02-15 [1] CRAN (R 4.0.2)                    
#>  lme4         * 1.1-27      2021-05-15 [1] CRAN (R 4.0.2)                    
#>  lmerTest       3.1-3       2020-10-23 [1] CRAN (R 4.0.2)                    
#>  magrittr       2.0.1       2020-11-17 [1] CRAN (R 4.0.2)                    
#>  MASS           7.3-53.1    2021-02-12 [1] CRAN (R 4.0.2)                    
#>  Matrix       * 1.3-2       2021-01-06 [1] CRAN (R 4.0.2)                    
#>  mime           0.11        2021-06-23 [1] CRAN (R 4.0.2)                    
#>  minqa          1.2.4       2014-10-09 [1] CRAN (R 4.0.0)                    
#>  munsell        0.5.0       2018-06-12 [1] CRAN (R 4.0.0)                    
#>  mvtnorm        1.1-2       2021-06-07 [1] CRAN (R 4.0.2)                    
#>  nlme           3.1-152     2021-02-04 [1] CRAN (R 4.0.2)                    
#>  nloptr         1.2.2.2     2020-07-02 [1] CRAN (R 4.0.2)                    
#>  numDeriv       2016.8-1.1  2019-06-06 [1] CRAN (R 4.0.0)                    
#>  openxlsx       4.2.3       2020-10-27 [1] CRAN (R 4.0.2)                    
#>  pillar         1.6.1       2021-05-16 [1] CRAN (R 4.0.2)                    
#>  pkgconfig      2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                    
#>  plyr           1.8.6       2020-03-03 [1] CRAN (R 4.0.0)                    
#>  purrr          0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                    
#>  R6             2.5.0       2020-10-28 [1] CRAN (R 4.0.2)                    
#>  Rcpp           1.0.6       2021-01-15 [1] CRAN (R 4.0.2)                    
#>  readxl         1.3.1       2019-03-13 [1] CRAN (R 4.0.0)                    
#>  reprex         2.0.0       2021-04-02 [1] CRAN (R 4.0.2)                    
#>  reshape2       1.4.4       2020-04-09 [1] CRAN (R 4.0.0)                    
#>  rio            0.5.26      2021-03-01 [1] CRAN (R 4.0.2)                    
#>  rlang          0.4.11.9000 2021-06-24 [1] Github (r-lib/rlang@9bed9dd)      
#>  rmarkdown      2.9.1       2021-06-20 [1] Github (rstudio/rmarkdown@bafed5e)
#>  scales         1.1.1       2020-05-11 [1] CRAN (R 4.0.0)                    
#>  sessioninfo    1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                    
#>  stringi        1.6.2       2021-05-17 [1] CRAN (R 4.0.2)                    
#>  stringr        1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                    
#>  styler         1.3.2       2020-02-23 [1] CRAN (R 4.0.0)                    
#>  tibble         3.1.2       2021-05-16 [1] CRAN (R 4.0.2)                    
#>  tidyselect     1.1.1       2021-04-30 [1] CRAN (R 4.0.2)                    
#>  utf8           1.2.1       2021-03-12 [1] CRAN (R 4.0.2)                    
#>  vctrs          0.3.8       2021-04-29 [1] CRAN (R 4.0.2)                    
#>  vipor          0.4.5       2017-03-22 [1] CRAN (R 4.0.2)                    
#>  withr          2.4.2       2021-04-18 [1] CRAN (R 4.0.2)                    
#>  xfun           0.24        2021-06-15 [1] CRAN (R 4.0.2)                    
#>  xml2           1.3.2       2020-04-23 [1] CRAN (R 4.0.0)                    
#>  xtable         1.8-4       2019-04-21 [1] CRAN (R 4.0.0)                    
#>  yaml           2.2.1       2020-02-01 [1] CRAN (R 4.0.2)                    
#>  zip            2.2.0       2021-05-31 [1] CRAN (R 4.0.2)                    
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Comment by singmann** [comment]
This is currently not possible, because the data you plot by adding a geom with `+` is the mean in the foreground. Sadly, `afex_plot()` does not offer the possibility of multiple geoms for the background (the idea is good, but it is a bit unclear how to make a good interface for this). However, you can get to what you want by using `return = "data"` in the `afex_plot()` call and then rebuilding the plot yourself. For example:

``` r
suppressPackageStartupMessages(library("afex"))
suppressPackageStartupMessages(library("ggplot2"))

data(md_12.1)
aw <- aov_ez("id", "rt", md_12.1, within = "noise")
#> Warning: More than one observation per cell, aggregating the data using mean
#> (i.e, fun_aggregate = mean)!

dp <- afex_plot(aw, x = "noise", return = "data")
#> Warning: Panel(s) show within-subjects factors, but not within-subjects error bars.
#> For within-subjects error bars use: error = "within"
ggplot(dp$means, aes(x = x, y = y)) +
  ggbeeswarm::geom_quasirandom(data = dp$data, alpha = 0.3) +
  geom_boxplot(data = dp$data, alpha = 0.3) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 2) +
  geom_point(size = 2)
```

![](https://i.imgur.com/cMt94g2.png)

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by shirdekel** [comment]
Ah that's a shame.

What about something like this:

    suppressPackageStartupMessages(library("afex"))
    suppressPackageStartupMessages(library("ggplot2"))

    data(md_12.1)
    aw <- aov_ez("id", "rt", md_12.1, within = "noise")
    #> Warning: More than one observation per cell, aggregating the data using mean
    #> (i.e, fun_aggregate = mean)!

    dp <- afex_plot(aw, x = "noise", return = "data")
    #> Warning: Panel(s) show within-subjects factors, but not within-subjects error bars.
    #> For within-subjects error bars use: error = "within"

    afex_plot_test <- function(dp,
                               data_geom = NULL,
                               data_arg = list(color = "darkgrey")) {
      p <- ggplot(dp$means, aes(x = x, y = y)) +
        geom_linerange(aes(ymin = lower, ymax = upper), size = 2) +
        geom_point(size = 3)
      if (!is.null(data_geom)) {
        if (!is.list(data_geom)) {
          data_geom <- list(data_geom)
          data_arg <- list(data_arg)
        }
        data_geom_list <-
          purrr::map2(
            data_geom,
            data_arg,
            ~ do.call(
              what = .x,
              args = c(
                data = list(dp$data),
                .y
              )
            )
          )
        p$layers <- c(data_geom_list, p$layers)
      }
      p
    }

    afex_plot_test(dp)

![](https://i.imgur.com/T3K5Y6W.png)


    afex_plot_test(dp, geom_boxplot)

![](https://i.imgur.com/4HkD0Dt.png)


    afex_plot_test(dp, ggbeeswarm::geom_quasirandom)

![](https://i.imgur.com/J5D7nSK.png)


    afex_plot_test(
      dp,
      list(geom_boxplot, ggbeeswarm::geom_quasirandom),
      list(list(color = "darkgrey"), list(color = "darkgrey"))
    )

![](https://i.imgur.com/4ToamB2.png)

<sup>Created on 2021-06-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Mojave 10.14.6        
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_AU.UTF-8                 
    #>  ctype    en_AU.UTF-8                 
    #>  tz       Australia/Sydney            
    #>  date     2021-06-26                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package      * version    date       lib source                            
    #>  abind          1.4-5      2016-07-21 [1] CRAN (R 4.0.0)                    
    #>  afex         * 0.28-1     2021-01-12 [1] CRAN (R 4.0.2)                    
    #>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                    
    #>  backports      1.2.1      2020-12-09 [1] CRAN (R 4.0.2)                    
    #>  beeswarm       0.3.1      2021-03-07 [1] CRAN (R 4.0.2)                    
    #>  boot           1.3-27     2021-02-12 [1] CRAN (R 4.0.2)                    
    #>  car            3.0-10     2020-09-29 [1] CRAN (R 4.0.2)                    
    #>  carData        3.0-4      2020-05-22 [1] CRAN (R 4.0.0)                    
    #>  cellranger     1.1.0      2016-07-27 [1] CRAN (R 4.0.0)                    
    #>  cli            2.5.0      2021-04-26 [1] CRAN (R 4.0.2)                    
    #>  coda           0.19-4     2020-09-30 [1] CRAN (R 4.0.2)                    
    #>  codetools      0.2-18     2020-11-04 [1] CRAN (R 4.0.2)                    
    #>  colorspace     2.0-1      2021-05-04 [1] CRAN (R 4.0.2)                    
    #>  crayon         1.4.1      2021-02-08 [1] CRAN (R 4.0.2)                    
    #>  curl           4.3.1      2021-04-30 [1] CRAN (R 4.0.2)                    
    #>  data.table     1.14.0     2021-02-21 [1] CRAN (R 4.0.2)                    
    #>  DBI            1.1.1      2021-01-15 [1] CRAN (R 4.0.2)                    
    #>  digest         0.6.27     2020-10-24 [1] CRAN (R 4.0.2)                    
    #>  dplyr          1.0.6      2021-05-05 [1] CRAN (R 4.0.2)                    
    #>  ellipsis       0.3.2      2021-04-29 [1] CRAN (R 4.0.2)                    
    #>  emmeans        1.5.4      2021-02-03 [1] CRAN (R 4.0.2)                    
    #>  estimability   1.3        2018-02-11 [1] CRAN (R 4.0.0)                    
    #>  evaluate       0.14       2019-05-28 [1] CRAN (R 4.0.0)                    
    #>  fansi          0.5.0      2021-05-25 [1] CRAN (R 4.0.2)                    
    #>  farver         2.1.0      2021-02-28 [1] CRAN (R 4.0.2)                    
    #>  forcats        0.5.1      2021-01-27 [1] CRAN (R 4.0.2)                    
    #>  foreign        0.8-81     2020-12-22 [1] CRAN (R 4.0.2)                    
    #>  fs             1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                    
    #>  generics       0.1.0      2020-10-31 [1] CRAN (R 4.0.2)                    
    #>  ggbeeswarm     0.6.0      2017-08-07 [1] CRAN (R 4.0.2)                    
    #>  ggplot2      * 3.3.4      2021-06-16 [1] CRAN (R 4.0.2)                    
    #>  glue           1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  gtable         0.3.0      2019-03-25 [1] CRAN (R 4.0.0)                    
    #>  haven          2.3.1      2020-06-01 [1] CRAN (R 4.0.0)                    
    #>  highr          0.9        2021-04-16 [1] CRAN (R 4.0.2)                    
    #>  hms            1.0.0      2021-01-13 [1] CRAN (R 4.0.2)                    
    #>  htmltools      0.5.1.1    2021-01-22 [1] CRAN (R 4.0.2)                    
    #>  httr           1.4.2      2020-07-20 [1] CRAN (R 4.0.2)                    
    #>  knitr          1.33       2021-04-24 [1] CRAN (R 4.0.2)                    
    #>  labeling       0.4.2      2020-10-20 [1] CRAN (R 4.0.2)                    
    #>  lattice        0.20-44    2021-05-02 [1] CRAN (R 4.0.2)                    
    #>  lifecycle      1.0.0      2021-02-15 [1] CRAN (R 4.0.2)                    
    #>  lme4         * 1.1-26     2020-12-01 [1] CRAN (R 4.0.2)                    
    #>  lmerTest       3.1-3      2020-10-23 [1] CRAN (R 4.0.2)                    
    #>  magrittr       2.0.1      2020-11-17 [1] CRAN (R 4.0.2)                    
    #>  MASS           7.3-54     2021-05-03 [1] CRAN (R 4.0.2)                    
    #>  Matrix       * 1.3-4      2021-06-01 [1] CRAN (R 4.0.2)                    
    #>  mime           0.10       2021-02-13 [1] CRAN (R 4.0.2)                    
    #>  minqa          1.2.4      2014-10-09 [1] CRAN (R 4.0.0)                    
    #>  multcomp       1.4-16     2021-02-08 [1] CRAN (R 4.0.2)                    
    #>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.0.0)                    
    #>  mvtnorm        1.1-1      2020-06-09 [1] CRAN (R 4.0.0)                    
    #>  nlme           3.1-152    2021-02-04 [1] CRAN (R 4.0.2)                    
    #>  nloptr         1.2.2.2    2020-07-02 [1] CRAN (R 4.0.2)                    
    #>  numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 4.0.0)                    
    #>  openxlsx       4.2.3      2020-10-27 [1] CRAN (R 4.0.2)                    
    #>  pillar         1.6.1      2021-05-16 [1] CRAN (R 4.0.2)                    
    #>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                    
    #>  plyr           1.8.6      2020-03-03 [1] CRAN (R 4.0.0)                    
    #>  purrr          0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                    
    #>  R6             2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                    
    #>  Rcpp           1.0.6      2021-01-15 [1] CRAN (R 4.0.2)                    
    #>  readxl         1.3.1      2019-03-13 [1] CRAN (R 4.0.0)                    
    #>  reprex         1.0.0      2021-01-27 [1] CRAN (R 4.0.2)                    
    #>  reshape2       1.4.4      2020-04-09 [1] CRAN (R 4.0.0)                    
    #>  rio            0.5.26     2021-03-01 [1] CRAN (R 4.0.2)                    
    #>  rlang          0.4.11     2021-04-30 [1] CRAN (R 4.0.2)                    
    #>  rmarkdown      2.8.1      2021-05-15 [1] Github (rstudio/rmarkdown@9e19405)
    #>  sandwich       3.0-0      2020-10-02 [1] CRAN (R 4.0.2)                    
    #>  scales         1.1.1      2020-05-11 [1] CRAN (R 4.0.0)                    
    #>  sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                    
    #>  statmod        1.4.35     2020-10-19 [1] CRAN (R 4.0.2)                    
    #>  stringi        1.6.2      2021-05-17 [1] CRAN (R 4.0.2)                    
    #>  stringr        1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                    
    #>  styler         1.3.2      2020-02-23 [1] CRAN (R 4.0.0)                    
    #>  survival       3.2-7      2020-09-28 [1] CRAN (R 4.0.2)                    
    #>  TH.data        1.0-10     2019-01-21 [1] CRAN (R 4.0.2)                    
    #>  tibble         3.1.2      2021-05-16 [1] CRAN (R 4.0.2)                    
    #>  tidyselect     1.1.1      2021-04-30 [1] CRAN (R 4.0.2)                    
    #>  utf8           1.2.1      2021-03-12 [1] CRAN (R 4.0.2)                    
    #>  vctrs          0.3.8      2021-04-29 [1] CRAN (R 4.0.2)                    
    #>  vipor          0.4.5      2017-03-22 [1] CRAN (R 4.0.2)                    
    #>  withr          2.4.2      2021-04-18 [1] CRAN (R 4.0.2)                    
    #>  xfun           0.22       2021-03-11 [1] CRAN (R 4.0.2)                    
    #>  xml2           1.3.2      2020-04-23 [1] CRAN (R 4.0.0)                    
    #>  xtable         1.8-4      2019-04-21 [1] CRAN (R 4.0.0)                    
    #>  yaml           2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                    
    #>  zip            2.1.1      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  zoo            1.8-8      2020-05-02 [1] CRAN (R 4.0.2)                    
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

Regardless, I appreciate the workaround, thanks!

**Comment by singmann** [comment]
First attempt to address this in new development version:

``` r
suppressPackageStartupMessages(library("afex"))
suppressPackageStartupMessages(library("ggplot2"))
data(md_12.1)
aw <- aov_ez("id", "rt", md_12.1, within = c("angle", "noise"))

### we can also use multiple geoms for the background by passing a list of geoms
afex_plot(aw, x = "noise", trace = "angle", error = "within", 
          data_geom = list(
            ggplot2::geom_violin, 
            ggplot2::geom_point
          ))
```

![](https://i.imgur.com/Sw7UZto.png)

``` r
## with separate extra arguments:

afex_plot(aw, x = "noise", trace = "angle", error = "within", 
          dodge = 0.5,
          data_geom = list(
            ggplot2::geom_violin, 
            ggplot2::geom_point
          ), 
          data_arg = list(
            list(width = 0.4, color = "darkgrey"),
            list(position = 
                   ggplot2::position_jitterdodge(
                     jitter.width = 0, 
                     jitter.height = 5, 
                     dodge.width = 0.5  ## needs to be same as dodge
                   ), color = "darkgrey"))
          )
```

![](https://i.imgur.com/fCfAusi.png)

``` r
afex_plot(aw, x = "angle", error = "within", 
          data_geom = 
            list(ggplot2::geom_violin, ggplot2::geom_boxplot), 
          data_arg = list(
            list(width = 0.7, color = "darkgrey"), 
            list(width = 0.2, color = "darkgrey")))
```

![](https://i.imgur.com/ux0dyIa.png)

``` r
data("fhch2010") # load 
fhch <- droplevels(fhch2010[ fhch2010$correct,]) # remove errors
### following model should take less than a minute to fit:
mrt <- mixed(log_rt ~ task*stimulus*frequency + (stimulus*frequency||id)+
               (task||item), fhch, method = "S", expand_re = TRUE)
#> Contrasts set to contr.sum for the following variables: task, stimulus, frequency, id, item
#> boundary (singular) fit: see help('isSingular')

afex_plot(mrt, "stimulus", "frequency", "task", id = "id", 
          data_geom = list(geom_violin, geom_point))
#> Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
#> To enable adjustments, add the argument 'pbkrtest.limit = 12960' (or larger)
#> [or, globally, 'set emm_options(pbkrtest.limit = 12960)' or larger];
#> but be warned that this may result in large computation time and memory use.
#> Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
#> To enable adjustments, add the argument 'lmerTest.limit = 12960' (or larger)
#> [or, globally, 'set emm_options(lmerTest.limit = 12960)' or larger];
#> but be warned that this may result in large computation time and memory use.
```

![](https://i.imgur.com/cfCWu1A.png)

<sup>Created on 2022-05-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by singmann** [comment]
I have now also added a new argument `data_color` that is automatically passed to all data geoms (i.e., similar to data_alpha). This makes specifying the extra arguments for the data geom somewhat easier. It can be disabled by using `data_color = NULL`, in case one wants to map by color.

To me this issue seems to be fixed now. Let me know if you have any comments, otherwise I will close this issue.

**Comment by shirdekel** [comment]
Looks good!
