### ISSUE TITLE
C_stri_join' not found

### ISSUE THREAD

**Issue by skanskan** [singmann/afex#11]
When I run any aov_ez()  or aov_car(), even the examples from the help, I get this error:

Error in stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE) : 
  object 'C_stri_join' not found

I've tried reinstalling stringi and stringr packages, but it doesn't fix the problem.

Regards

**Comment by singmann** [comment]
Can you post your `sessionInfo()`? I have no problems hence I assume the problem is an old version of something along the line? Perhaps an old version of `R`?

**Comment by singmann** [comment]
problem seems to have disappeared.
