### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [singmann/afex#114]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that your package somehow includes references to ggplot2 code from when it was build, either by reloading saved plot objects or by grabbing functions at build time. Please see https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/ for some more info about why this can cause issues.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by singmann** [comment]
Thanks for your report. I fixed it and pushed a version that should work with latest `ggplot2` to CRAN.

**Comment by eclarke** [comment]
Hi @singmann, I am working on releasing a new version of `ggbeeswarm` and am encountering a similar issue when CRAN performs its reverse-dependency checks:

```
--- re-building ‘afex_plot_supported_models.Rmd’ using rmarkdown
 Quitting from lines 245-247 (afex_plot_supported_models.Rmd) 
 Error: processing vignette ‘afex_plot_supported_models.Rmd’ failed with diagnostics:
 Problem while computing position.
 ℹ Error occurred in the 1st layer.
 Caused by error in `if (method %in% c("swarm", "compactswarm")) ...`:
 ! argument is of length zero
```

This appears to be related to the `extdata/plots_rstanarm.rda` file loaded in line 245. There are no other errors in the vignettes, which leads me to believe this error is related to changes in the internal plot objects and not from any changes to the `ggbeeswarm` interface.

I can also confirm that this error occurs using both the CRAN version of `afex` and the most recent version on Github.
