### ISSUE TITLE
Issue with upcoming ggplot2 version

### ISSUE THREAD

**Issue by teunbrand** [singmann/afex#119]
Hi there,

While preparing for a new release of ggplot2, our reverse dependency check showed that your package's vignette has broken.
More specifically, we believe that the vignette can no longer be built due to plots being saved to disk.
We generally don't recommend saving plots to disk, partially because the saved objects may contain internal code that is version dependent.
ggplot2 tries to keep the exported functions stable, but makes no promise about internal code.
In this case, such an internal function has changed (for appealing reasons), but it invalidates plots saved to disk with previous versions of ggplot2.

In particular, we believe that the plots saved in the file below have become invalid:

```
inst/extdata/outputs_glmm_vignette.rda
```

If it is very inconvenient to circumvent saving plots to disk, please consider this issue an advance warning. The saved plots might have to be regenerated with the upcoming version of ggplot2. You can test the upcoming changes with the current release candidate, that can be installed with devtools::install_github('tidyverse/ggplot2@v3.4.2-rc').

Best wishes,
Teun

**Comment by singmann** [comment]
My problem has been for a while that the plot is based on an expensive to compute model object that is also large in size. So neither saving the model nor recalculating it works while building the vignette. So far, I have saved the plot object itself, but this seems to run into problems such as this regularly. 

So my question is, if there is a better way. Can I for example first transform my plot into a list using `ggplot_build()` and then save that resulting object? Will I be able to re-plot the returned object in the future even if `ggplot2` internals change if I use `print()`?

**Comment by singmann** [comment]
Thanks, I will try this out for all vignettes. Just need to find the time in the next days to do it for all vignettes. When done, will close this issue and update on CRAN.
