### ISSUE TITLE
Two sets of errors using mixed on a glmm

### ISSUE THREAD

**Issue by BryanMaloney** [singmann/afex#15]
I have the following data:

   Patient Day Cluster    APP_ml
1      P54   1    High 10.656200
2      P54   2    High  4.353180
3      P54   3    High 22.294005
4      P54   4    High  8.548865
5      P54   5    High 16.959220
6      P64   1    High  9.896800
7      P64   2    High  7.637585
8      P64   3    High  9.744920
9      P64   4    High 11.187780
10     P64   5    High 11.453570
11     P70   1     Low  3.840585
12     P70   2     Low  5.226490
13     P70   3     Low  4.429120
14     P70   4     Low  8.396985
15     P70   5     Low  6.631380
19     P71   1    High 12.307895
20     P71   2    High  4.068405
21     P71   3    High  5.397355
22     P71   4    High 18.515990
23     P71   5    High 32.280115
26     P72   1    High 15.041735
27     P72   2    High  6.346605
28     P72   3    High  7.998300
29     P72   4    High  9.763905
30     P75   1     Low  2.416710
31     P75   2     Low  3.119155
32     P75   3     Low  7.542660
33     P75   4     Low  5.473295
34     P75   5     Low  6.327620
37     P76   1     Low  6.004875
38     P76   2     Low  3.365960
39     P76   3     Low 10.371425
40     P76   4     Low  4.448105
41     P77   1     Low  4.315210
42     P77   2     Low  1.353550
43     P77   3     Low  6.194725
44     P77   4     Low  5.815025
45     P77   5     Low 12.839475
48     P78   1     Low  7.068035
49     P78   2     Low 14.586095
50     P78   3     Low 23.547015
51     P78   4     Low 11.111840
52     P78   5     Low 14.548125
54     P79   1     Low  4.922730
55     P79   2     Low  6.574425
56     P79   3     Low  9.877815
57     P79   4     Low  5.966905
58     P79   5     Low  8.985520
60     P80   1    High 11.035900
61     P80   2    High 12.744550
62     P80   3    High 20.490430
63     P80   4    High 22.483855
64     P82   1    High  9.175370
65     P82   2    High  5.739085
66     P82   3    High  5.890965
67     P82   4    High  6.099800

I have the following model:
allmod.full<- glmer(APP_ml ~ Cluster * Day + (1+Day|Patient), data = APP.daytrim, family = Gamma(link = "identity"), glmerControl(optimizer = "bobyqa"))

This works nicely.

I try the following:
foo<-mixed(formula(allmod.m.trim),method="LRT",data=APP.daytrim,family=Gamma(link="identity"),options(glmerControl(optimizer = "bobyqa")))

I get the following:
Error in mixed(formula(allmod.m.trim), method = "LRT", data = APP.daytrim,  : 
  (list) object cannot be coerced to type 'double'

So, I do this model:
allmod.full<- glmer(APP_ml ~ Cluster * Day + (1+Day|Patient), data = APP.daytrim, family = Gamma(link = "identity"))

It converges nicely, too.

So, I try this:
foo<-mixed(formula(allmod.m.trim),method="LRT",data=APP.daytrim,family=Gamma(link="identity"))

And I get this:
Warning message:
In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0264542 (tol = 0.001, component 1)

What am I doing wrong?

**Comment by BryanMaloney** [comment]
I found it! When I set it to "check.contrasts = false", I get convergence. Since there is no need for sum-to-zero contrasts in this model, this works nicely.

**Comment by singmann** [comment]
Sorry for the long delay. I am not sure what you want to achieve, but there seem to be some problems with your code. 
But even when repairing those problems, note that using `Type III` tests, which is the default in `mixed`, tests the lower-order effects (e.g., main effects) at the origin of each variable (i.e., when they are zero). That is why using sum-to-zero contrasts is indicted. This means, when `Day` is treated as numerical, the test of `Cluster` is performed at `Day` equal to zero, which seems somewhat silly (may be not, but given my limited information). So removing the test for correct contrasts is also probably not a good idea. 

Finally, convergence warning may or may not indicate a problem. But it is clearly better to have convergence problems that non-sensical test. So I would be really careful in removing this check and when including numerical covariates. 

Let me know if this makes sense. Below my code for your example.

```
dat <- read.table(text = "Patient Day Cluster APP_ml
1 P54 1 High 10.656200
2 P54 2 High 4.353180
3 P54 3 High 22.294005
4 P54 4 High 8.548865
5 P54 5 High 16.959220
6 P64 1 High 9.896800
7 P64 2 High 7.637585
8 P64 3 High 9.744920
9 P64 4 High 11.187780
10 P64 5 High 11.453570
11 P70 1 Low 3.840585
12 P70 2 Low 5.226490
13 P70 3 Low 4.429120
14 P70 4 Low 8.396985
15 P70 5 Low 6.631380
19 P71 1 High 12.307895
20 P71 2 High 4.068405
21 P71 3 High 5.397355
22 P71 4 High 18.515990
23 P71 5 High 32.280115
26 P72 1 High 15.041735
27 P72 2 High 6.346605
28 P72 3 High 7.998300
29 P72 4 High 9.763905
30 P75 1 Low 2.416710
31 P75 2 Low 3.119155
32 P75 3 Low 7.542660
33 P75 4 Low 5.473295
34 P75 5 Low 6.327620
37 P76 1 Low 6.004875
38 P76 2 Low 3.365960
39 P76 3 Low 10.371425
40 P76 4 Low 4.448105
41 P77 1 Low 4.315210
42 P77 2 Low 1.353550
43 P77 3 Low 6.194725
44 P77 4 Low 5.815025
45 P77 5 Low 12.839475
48 P78 1 Low 7.068035
49 P78 2 Low 14.586095
50 P78 3 Low 23.547015
51 P78 4 Low 11.111840
52 P78 5 Low 14.548125
54 P79 1 Low 4.922730
55 P79 2 Low 6.574425
56 P79 3 Low 9.877815
57 P79 4 Low 5.966905
58 P79 5 Low 8.985520
60 P80 1 High 11.035900
61 P80 2 High 12.744550
62 P80 3 High 20.490430
63 P80 4 High 22.483855
64 P82 1 High 9.175370
65 P82 2 High 5.739085
66 P82 3 High 5.890965
67 P82 4 High 6.099800")

dat$Day <- factor(dat$Day)
str(dat)

allmod.full<- glmer(APP_ml ~ Cluster * Day + (1+Day|Patient), data = dat, family = Gamma(link = "identity"), control = glmerControl(optimizer = "bobyqa"))

foo<-mixed(APP_ml ~ Cluster * Day + (1+Day|Patient),method="LRT",data=dat,family=Gamma(link="identity"),control = glmerControl(optimizer = "bobyqa"))

car::Anova(allmod.full, type = 3)  # very similar resuls.
```

**Comment by BryanMaloney** [comment]
I should have sum-to-zero contrasts only for the fixed effects or also random effects? 

    On Thursday, April 14, 2016 7:51 AM, singmann <notifications@github.com> wrote:
 

 Sorry for the long delay. I am not sure what you want to achieve, but there seem to be some problems with your code. 
But even when repairing those problems, note that using Type III tests, which is the default in mixed, tests the lower-order effects (e.g., main effects) at the origin of each variable (i.e., when they are zero). That is why using sum-to-zero contrasts is indicted. This means, when Day is treated as numerical, the test of Cluster is performed at Day equal to zero, which seems somewhat silly (may be not, but given my limited information). So removing the test for correct contrasts is also probably not a good idea. Finally, convergence warning may or may not indicate a problem. But it is clearly better to have convergence problems that non-sensical test. So I would be really careful in removing this check and when including numerical covariates. Let me know if this makes sense. Below my code for your example.dat <- read.table(text = "Patient Day Cluster APP_ml
1 P54 1 High 10.656200
2 P54 2 High 4.353180
3 P54 3 High 22.294005
4 P54 4 High 8.548865
5 P54 5 High 16.959220
6 P64 1 High 9.896800
7 P64 2 High 7.637585
8 P64 3 High 9.744920
9 P64 4 High 11.187780
10 P64 5 High 11.453570
11 P70 1 Low 3.840585
12 P70 2 Low 5.226490
13 P70 3 Low 4.429120
14 P70 4 Low 8.396985
15 P70 5 Low 6.631380
19 P71 1 High 12.307895
20 P71 2 High 4.068405
21 P71 3 High 5.397355
22 P71 4 High 18.515990
23 P71 5 High 32.280115
26 P72 1 High 15.041735
27 P72 2 High 6.346605
28 P72 3 High 7.998300
29 P72 4 High 9.763905
30 P75 1 Low 2.416710
31 P75 2 Low 3.119155
32 P75 3 Low 7.542660
33 P75 4 Low 5.473295
34 P75 5 Low 6.327620
37 P76 1 Low 6.004875
38 P76 2 Low 3.365960
39 P76 3 Low 10.371425
40 P76 4 Low 4.448105
41 P77 1 Low 4.315210
42 P77 2 Low 1.353550
43 P77 3 Low 6.194725
44 P77 4 Low 5.815025
45 P77 5 Low 12.839475
48 P78 1 Low 7.068035
49 P78 2 Low 14.586095
50 P78 3 Low 23.547015
51 P78 4 Low 11.111840
52 P78 5 Low 14.548125
54 P79 1 Low 4.922730
55 P79 2 Low 6.574425
56 P79 3 Low 9.877815
57 P79 4 Low 5.966905
58 P79 5 Low 8.985520
60 P80 1 High 11.035900
61 P80 2 High 12.744550
62 P80 3 High 20.490430
63 P80 4 High 22.483855
64 P82 1 High 9.175370
65 P82 2 High 5.739085
66 P82 3 High 5.890965
67 P82 4 High 6.099800")

dat$Day <- factor(dat$Day)
str(dat)

allmod.full<- glmer(APP_ml ~ Cluster * Day + (1+Day|Patient), data = dat, family = Gamma(link = "identity"), control = glmerControl(optimizer = "bobyqa"))

foo<-mixed(APP_ml ~ Cluster * Day + (1+Day|Patient),method="LRT",data=dat,family=Gamma(link="identity"),control = glmerControl(optimizer = "bobyqa"))

car::Anova(allmod.full, type = 3)  # very similar resuls.

**Comment by singmann** [comment]
For the fixed effects estimates and Type III tests it is necessary to use sum-to-zero contrasts if you want to interpret lower-order effects in the presence of higher-order effects (e.g., main effects when the model includes interactions). 

The same is also true for the random effects estimates if you want to interpret them. If you just treat them as nuisance parameters that is obviously not so important.
