### ISSUE TITLE
aov_car does not cope with column names with spaces in them (or other special chars)

### ISSUE THREAD

**Issue by jonathon-love** [singmann/afex#22]
```
data <- list("dependent" = rnorm(100), "RM Factor 1" = factor(rep(c("Level 1", "Level 2"), 50)), "subject" = factor(rep(1:50, each = 2)))

attr(data, 'row.names') <- seq_len(length(data[[1]]))
attr(data, 'class') <- 'data.frame'

formula <- as.formula("dependent ~ `RM Factor 1` + Error(subject/(`RM Factor 1`))")

afex::aov_car(formula, data)
```

**Comment by singmann** [comment]
Hi Jonathan,

thanks to your fix, the following two now work:

    aov_car(dependent ~ `RM Factor 1` + Error(subject/(`RM Factor 1`)), data)
    aov_4(dependent ~ `RM Factor 1` + (`RM Factor 1`|subject), data)

However, using `aov_ez` still fails:

    aov_ez("id", "dependent", data, within = "`RM Factor 1`")
    ##  Error in `[.data.frame`(data, , id) : undefined columns selected 

Are you willing to commit a fix for this as well?

**Comment by jonathon-love** [comment]
sure, i'll take a look.

**Comment by jonathon-love** [comment]
actually, this all works fine, your call to `aov_ez()` has two errors in it, it should be:
```
afex::aov_ez("subject", "dependent", data, within = "RM Factor 1")
```

**Comment by singmann** [comment]
okay, thanks. Good to know that I am too stupid to use my own package...

**Comment by jonathon-love** [comment]
:P
