### ISSUE TITLE
Significance asterisks

### ISSUE THREAD

**Issue by SunByrne** [singmann/afex#37]
Significance asterisks should appear after the _p_-value, not the _F_-value. What afex produces looks like this:

```
Response: SpecLen
         Effect      df  MSE       F ges p.value
1        BlockF   4, 16 6.51 7.35 ** .27    .001
2        TrialF   9, 36 0.67    1.19 .01     .33
3 BlockF:TrialF 36, 144 0.90    1.35 .08     .11
```

but in order to maintain consistency with pretty much every other R table, it really should look like this:

```
Response: SpecLen
         Effect      df  MSE       F ges p.value
1        BlockF   4, 16 6.51    7.35 .27    .001 **
2        TrialF   9, 36 0.67    1.19 .01     .33
3 BlockF:TrialF 36, 144 0.90    1.35 .08     .11
```

**Comment by singmann** [comment]
I think I did this to be compatible with APA standard. However, I cannot find my APA manual copy right now to check this. But I am pretty sure about it.
If you want the R default just use the `anova()` method and not the `nice()` method for an  object of class `afex_aov` (note that the `nice()` method is called for printing). e.g.:

```
require(afex)

data(md_12.1)
a <- aov_ez("id", "rt", md_12.1, within = c("angle", "noise"), 
       anova_table=list(correction = "HF", es = "none"))
nice(a)
# Anova Table (Type 3 tests)
# 
# Response: rt
#        Effect    df     MSE         F p.value
# 1       angle 2, 18 3560.00 40.72 ***  <.0001
# 2       noise  1, 9 8460.00 33.77 ***   .0003
# 3 angle:noise 2, 18 1160.00 45.31 ***  <.0001
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
# 
# Sphericity correction method: HF 
# Warning message:
# HF eps > 1 treated as 1 

anova(a)
# Anova Table (Type 3 tests)
# 
# Response: rt
#             num Df den Df    MSE      F     ges    Pr(>F)    
# angle       1.9233 17.309 3702.0 40.719 0.39012 3.402e-07 ***
# noise       1.0000  9.000 8460.0 33.766 0.38660  0.000256 ***
# angle:noise 1.8080 16.272 1283.2 45.310 0.18827 3.454e-07 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

I think this solves this issue.

**Comment by singmann** [comment]
PS: R default is also not to round the p-values in the ways that `nice()` does. I very much prefer the rounding as well.

**Comment by SunByrne** [comment]
I prefer the rounded _p_-values but I'm looking at the APA manual right in front of me and I don't see anything about asterisks on _F_-values.

**Comment by singmann** [comment]
I think an example ANOVA table was in the 5th edition handbook. But I cannot find a copy of it around here. Only the new 6th edition. 

But note that in the example tables in the new version, the asterisks are usually also with the test statistics. This is also done in afex. I agree that there are no tables that have both test statistics and p-values, but still I am convinced it is better like that.

**Comment by SunByrne** [comment]
The APA manual specifies that in tables, columns of numbers should be decimal-aligned. Putting the asterisks on makes them not decimal-aligned.

**Comment by singmann** [comment]
I feel like the alignment question cannot be solve in R (or not without a lot of headache). This needs to be done with whatever software you write your papers. If you want no stars, you can easily ask for no stars. 

As I said before, if you want the R default, use the `anova()` method. If you want what I find better, use the `nice()` method. If you want something that is in between the R default and the `nice()` method, then you have to program it on your own. I like the stars with the F-values and I believe this is how it was supposed to be in the previous APA version. You will need a really good argument to change the default `nice()` output and so far your arguments were not really strong.
