### ISSUE TITLE
Transition from lsmeans to emmeans

### ISSUE THREAD

**Issue by jonathon-love** [singmann/afex#38]
hi henrik,

i sat down the other day to begin looking into what it would take to transition `afex` from `lsmeans` to `emmeans`, but then i noticed the `emmeans` branch! anyhow, i'm creating this issue so i (and others) can track your progress :)

we'll transition `jmv` over to `emmeans` once `afex` is ready.

let me know if you need any assistance with anything.

with thanks

**Comment by singmann** [comment]
Hi Jonathon,

Thanks for reminding me that I need to get this on track. Most stuff is already in place. I only need to update the tests. Should be done somewhat soonish (yeah, yeah). 

Cheers,

**Comment by singmann** [comment]
Hi Jonathon,

`afex` with `emmeans` support was updated on CRAN last week.
