### ISSUE TITLE
Documentation glitch for afex_aov methods

### ISSUE THREAD

**Issue by rvlenth** [singmann/afex#44]
Henrik,

I notice that the help page for afex_aov methods includes the text:

> recover_data and emm_basis
> Provide the backbone for using emmeans and related functions from emmeans directly on afex_aov objects by returning a ref.grid object. Should not be called directly but through the functionality provided by emmeans.

You should replace `ref.grid` here with `emmGrid` (and also replace its link). Not a big issue but worth correcting before your next update.

Cheers,

Russ

**Comment by singmann** [comment]
Thanks for the message. I have changed it in the roxygen2 code so it will update next time I recompile the documentation (I can only do that on my other machine).
