### ISSUE TITLE
Add `sphericity()` function/method

### ISSUE THREAD

**Issue by singmann** [singmann/afex#55]
`afex_aov` objects should have a method that returns the test of sphericity for within-subject ANOVAs. This would allow the following coding style (which some might like):
```
library("afex")
data(obk.long, package = "afex")

# estimate mixed ANOVA on the full design:
a1 <- aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
        data = obk.long, observed = "gender")
sphericity(a1)
nice(a1, correction = "HF")
```

Maybe something similar for Levene tests would be nice as well (e.g., based on `leveneTest()` in `car`).

Both ideas are based on discussions with Charlotte Tate.

**Comment by mattansb** [comment]
I've written some functions for testing ANOVA assumptions for an applied stats course I'm teaching, that integrate with `afex` (my go-to anova package), that I thought might be useful to post here.

``` r

# Functions ---------------------------------------------------------------

afex_leveneTest <- function(afex_aov, center = mean, ...){
  `%>%` <- dplyr::`%>%`
  data <- afex_aov$data$long
  dv <- attr(afex_aov,'dv')
  id <- attr(afex_aov,'id')
  between <- names(attr(afex_aov,'between'))
  funs <- list(mean)
  names(funs) <- dv

  form <- formula(paste0(dv,'~',paste0(between,collapse = '*')))
  ag_data <- data %>%
    dplyr::group_by_at(c(between,id)) %>%
    dplyr::summarise_at(dv,funs)

  car::leveneTest(form,ag_data, center = center, ...)
}

afex_sphericityTest<- function(afex_aov){
  summary(afex_aov)$sphericity.tests
}

afex_qqplot_residuals <- function(afex_aov, show.plot = TRUE) {
  `%>%` <- dplyr::`%>%`

  aov_fit <- afex_aov$aov
  X <- proj(aov_fit)

  if (!is.list(X)) X <- list(X)

  res_vals <- X %>%
    purrr::map(as.data.frame) %>%
    purrr::map('Residuals')

  res_names <- X %>%
    purrr::map(~attr(.x,"factors")$Residuals) %>%
    purrr::map_chr(paste0,collapse = ':')

  remove_ <- purrr::map_lgl(res_vals,is.null)
  res_vals <- res_vals[!remove_]
  res_names <- res_names[!remove_]
  names(res_vals) <- res_names

  if (show.plot) {
    for (v in seq_along(res_names)) {
      invisible(readline(paste0("Press [enter] for '",res_names[v],"' qqplot")))
      qqnorm(res_vals[[v]],main = res_names[v])
      qqline(res_vals[[v]])
    }
    return(invisible(res_vals))
  } else {
    return(res_vals)
  }
}


# Test --------------------------------------------------------------------

library(afex)

data(obk.long, package = "afex")

fit <- aov_ez('id','value',obk.long,
              between = c('treatment','gender'),
              within = c('phase','hour'))
#> Contrasts set to contr.sum for the following variables: treatment, gender

afex_leveneTest(fit)
#> Levene's Test for Homogeneity of Variance (center = center)
#>       Df F value Pr(>F)
#> group  5  1.2671 0.3497
#>       10

afex_sphericityTest(fit)
#>                             Test statistic p-value
#> phase                              0.74927 0.27282
#> treatment:phase                    0.74927 0.27282
#> gender:phase                       0.74927 0.27282
#> treatment:gender:phase             0.74927 0.27282
#> hour                               0.06607 0.00760
#> treatment:hour                     0.06607 0.00760
#> gender:hour                        0.06607 0.00760
#> treatment:gender:hour              0.06607 0.00760
#> phase:hour                         0.00478 0.44939
#> treatment:phase:hour               0.00478 0.44939
#> gender:phase:hour                  0.00478 0.44939
#> treatment:gender:phase:hour        0.00478 0.44939

afex_qqplot_residuals(fit)
#> Press [enter] for 'id' qqplot
```

![](https://i.imgur.com/BSHa18a.png)

    #> Press [enter] for 'id:phase' qqplot

![](https://i.imgur.com/pPonnms.png)

    #> Press [enter] for 'id:hour' qqplot

![](https://i.imgur.com/RD8c9qJ.png)

    #> Press [enter] for 'id:phase:hour' qqplot

![](https://i.imgur.com/hk5pLbx.png)

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by singmann** [comment]
@mattansb That looks pretty great, thanks so much for addressing this issue. I would be happy if something like this could be added to `afex`. However, I would not be willing to accept this as a pull request as it currently stands. The main reason for this is that it would somewhat substantially increase the dependencies of `afex` via the [`tidyverse` tax](http://dirk.eddelbuettel.com/blog/2015/07/26/#evading_the_hadley_tax_faster_travis_tests). I try to keep `afex` as lean as possible so I would not be willing to add `dplyr` and `purrr` as imports.

I see two possibilities to address this: Either change the code and remove the dependencies on `dplyr` and `purrr` with corresponding base `R` functions. This would probably be the cleaner option. Or add appropriate `requireNamespace()` calls to the function (see e.g., [`afex_plot`](https://github.com/singmann/afex/blob/9fa326c3145fe836a2c89f10cbc99050fb6acb04/R/afex_plot.R#L778)). This would probably also be fine, as only `purrr` is not yet in `Suggests`. Maybe a  compromise could be to replace the `purrr` calls with `lapply` and `vapply` (last one) and keep the `dplyr` stuff with the `requireNamespace()` calls at the beginning. In this case, nothing would be added to the existing dependencies.

Also, is there a way to get residuals based on the `lm` model for repeated-measure designs? I am planning to retire the `aov` slot eventually, so would be somewhat wary of adding new functionality that requires it (currently it is not technically needed anymore for follow-up tests, so I do not see any real reason to keep it other than backward compatinility).

Finally, is there any chance to also offer the possibility to use `ggplot2` functions instead of base plot? I know that this seems somewhat in opposition to the previous statement about the `tidyverse` tax, but `afex_plot` also uses `ggplot2` and `ggplot2` plots would therefore provide a more coherent user experience.

**Comment by mattansb** [comment]
@singmann I think I did everything on your list (:
The only workaround for not using the `aov` slot was to create the `aovlist` object inside the function. Is it pretty? No. But does it work? Yes.
I also changed the functions' names, but of course that is completely up to you.

``` r
# Functions ---------------------------------------------------------------

leveneTest <- function (y, ...) { # so this can play nice with `car`'s methods?
  UseMethod("leveneTest")
}

leveneTest.afex_aov <- function(afex_aov, center = mean, ...){
  data <- afex_aov$data$long
  dv <- attr(afex_aov,'dv')
  id <- attr(afex_aov,'id')
  between <- names(attr(afex_aov,'between'))
  
  form <- formula(paste0(dv,'~',paste0(between,collapse = '*')))
  
  ag_data <- aggregate(data[,dv],data[,c(between,id)],mean)
  colnames(ag_data)[length(c(between,id))+1] <- dv
  
  car::leveneTest(form,ag_data, center = center, ...)
}

sphericityTest<- function(afex_aov){
  summary(afex_aov)$sphericity.tests
}

residuals_qqplot <- function(afex_aov, return = 'plot') {
  # get aovlist
  data <- afex_aov$data$long
  dv <- attr(afex_aov,'dv')
  id <- attr(afex_aov,'id')
  between <- names(attr(afex_aov,'between'))
  within <- names(attr(afex_aov,'within'))
  
  lhs <- paste0(c(within,between),collapse = '*')
  err <- ''
  if (!is.null(within)) {
    err <- paste0('+Error(',id,'/(',paste0(within,collapse = '*'),'))')
  }
  
  form <- formula(paste0(dv,'~',lhs,err))
  
  aov_fit <- aov(form,data)
  
  # get residuals
  aov_proj <- proj(aov_fit)
  
  if (!is.list(aov_proj)) aov_proj <- list(aov_proj)
  
  res_vals <- lapply(lapply(aov_proj, as.data.frame),function(X) X[['Residuals']])
  
  res_names <- lapply(aov_proj, function(X) attr(X,"factors")$Residuals)
  res_names <- sapply(res_names,paste0,collapse = ':')
  
  remove_ <- sapply(res_vals,is.null)
  res_vals <- res_vals[!remove_]
  res_names <- res_names[!remove_]
  names(res_vals) <- res_names
  
  if (return=='plot') {
    # plot
    plot_data <- data.frame(x    = unlist(res_vals),
                            proj = unlist(lapply(res_names, function(X) rep(X,nrow(data)))),
                            row.names = NULL)
    
    ggplot(plot_data,aes(sample = x)) + 
      geom_qq() + 
      geom_qq_line() + 
      facet_wrap(~proj)
  } else {
    return(res_vals)
  }
}

# Test --------------------------------------------------------------------

library(afex)
library(ggplot2) # for residuals_qqplot

data(obk.long, package = "afex")

fit <- aov_ez('id','value',obk.long,
              between = c('treatment','gender'),
              within = c('phase','hour'))
#> Contrasts set to contr.sum for the following variables: treatment, gender

leveneTest(fit)
#> Levene's Test for Homogeneity of Variance (center = center)
#>       Df F value Pr(>F)
#> group  5  1.2671 0.3497
#>       10
sphericityTest(fit)
#>                             Test statistic p-value
#> phase                              0.74927 0.27282
#> treatment:phase                    0.74927 0.27282
#> gender:phase                       0.74927 0.27282
#> treatment:gender:phase             0.74927 0.27282
#> hour                               0.06607 0.00760
#> treatment:hour                     0.06607 0.00760
#> gender:hour                        0.06607 0.00760
#> treatment:gender:hour              0.06607 0.00760
#> phase:hour                         0.00478 0.44939
#> treatment:phase:hour               0.00478 0.44939
#> gender:phase:hour                  0.00478 0.44939
#> treatment:gender:phase:hour        0.00478 0.44939
residuals_qqplot(fit,'plot')
```

![](https://i.imgur.com/oV9xmnA.png)

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by singmann** [comment]
@mattansb Looks great. Can you create a pull request for that? For this, please create a new `.R` file in the `R` folder of the package and ideally with some bare bone `roxygen2` documentation. There are still some things to discuss, but then I can make moire concrete comments and also changes. One word of warning regarding timing, I am in marking stress this week and travelling next week, but will try to attend to this as quickly as possible.

**Comment by mattansb** [comment]
@singmann I think I made a pull request. Changed the function names to not conflict with `car`'s methods.

**Comment by mattansb** [comment]
sorry for the multiple PRs...

**Comment by singmann** [comment]
Sorry for the slow response. I hope to get to this later this week.

**Comment by singmann** [comment]
Has been added in #69.

**Comment by singmann** [comment]
Version `0.24-1` was just accepted on CRAN which adds the sphericity and Levene tests to the package. Thanks again @mattansb, I have also added you as an author to the package. I apologize that the residuals tests did not make it into this update. Hopefully next version.

**Comment by mattansb** [comment]
My pleasure @singmann !
