### ISSUE TITLE
Importing with rpy2

### ISSUE THREAD

**Issue by rkd1** [singmann/afex#58]
Dear afex Experts,

I am attempting to import this packaged in jupyter notebook, using rpy2, and am getting an error, pasted below. As can be seen, previous package importation works okay, but for some reason afex does not work. Does anyone know how to troubleshoot this?

FYI: This is done through anaconda's jupyter notebook on a Mac, using rpy2 version: 2.9.1 and R version: ('3', '4.3', '', 73796).

`#Importing key libraries from python.

import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import matplotlib.lines as mlines
from matplotlib import pyplot as plt
from statsmodels.formula.api import ols

# Import rpy2 and get version info.
import rpy2

### Importing key rpy2 top-level package for interfacing python with R.

​

import rpy2.robjects as robjects

from rpy2.robjects.packages import importr

​

# Importing r specific package as python objects

​

# import R's "base" package

base = importr('base')

​

# import R's "utils" package

utils = importr('utils')

​

# inport R's "afex" package

afex = importr('afex')

/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: Error in loadNamespace(name) : there is no package called ‘afex’

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: In addition: 
  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: There were 50 or more warnings (use warnings() to see the first 50)
  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)

---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
<ipython-input-27-eeaefb0a6e00> in <module>()
     13 
     14 # inport R's "afex" package
---> 15 afex = importr('afex')

/anaconda3/lib/python3.6/site-packages/rpy2/robjects/packages.py in importr(name, lib_loc, robject_translations, signature_translation, suppress_messages, on_conflict, symbol_r2python, symbol_check_after, data)
    451     if _package_has_namespace(rname, 
    452                               _system_file(package = rname)):
--> 453         env = _get_namespace(rname)
    454         version = _get_namespace_version(rname)[0]
    455         exported_names = set(_get_namespace_exports(rname))

RRuntimeError: Error in loadNamespace(name) : there is no package called ‘afex’
`

Thanks,
rkd1

**Comment by singmann** [comment]
Despite the somewhat suboptimal formatting of this message, it says it relatively clearly: `there is no package called ‘afex’`

The solution is to install the package beforehand. In `R` this is usually done via: `install.packages("afex")`. I have no idea what is the correct solution within `Jupyter`.

Note that installing usually only needs to be done with each version of `R` and `afex`. So not every time the package is needed.

**Comment by rkd1** [comment]
Dear Singmann,
My apologies for the messy formatting of the previous inquiry (I am very new to GitHub, but learning) and thank you for the quick response.

I believe that the command I used is the installation command (I tried this separately in R as well, as you suggested). It seems to work and install other packages (see below for examples), but seems to have issues with 'afex'.

I am wondering if this might be an issue with 'rpy2' commands, rather than 'afex' package. From your perspective, would you mind confirming whether there might be anything intrisically different with 'afex' package, in comparison to other packages below in terms of installation? This would help me rule out some issues.

Here is the code:
'from rpy2.robjects.packages import importr
base = importr('base')
utils = importr('utils')
ggplot2 = importr('ggplot2')
afex = importr('afex')
Error message:
/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: Error in loadNamespace(name) : there is no package called ‘afex’'

Note: the error message only comes up when installing 'afex' but not other packages. 
Thank you for your feedback.

**Comment by singmann** [comment]
Does this solve the issue? If so, I will close it.

**Comment by rkd1** [comment]
The issue is not solved. However, it is likely an issue with rpy2, rather than 'afex', so I will follow up in another location. Thank you for the quick responses!

**Comment by singmann** [comment]
As this was not an `afex` problem, the issue was closed.
