### ISSUE TITLE
How are unbalanced designs dealt with?

### ISSUE THREAD

**Issue by mattansb** [singmann/afex#63]
Hi Henrik,
Was working on an example for a stats class showing how unbalanced designs in ANOVA can cause "fake" effects, but ran into some differences between `afex`'s `aov_4` and base-`stats`'s `aov`:

I simulated some 2*2 between subject data with one main effect and one interaction when examining the means (the data can be found [here](https://drive.google.com/open?id=1C_Dkt7cWs0lnuSzeYPMxNq7u5S7KzyU2)), but with unequal cell sizes, causing a confounding between cell placement between the factors.
````
> some_data <- read.csv(choose.files())
> 
> cell_data <- split(some_data$y,interaction(some_data$A,some_data$B))
> unlist(lapply(cell_data,mean)) # the means for each cell - no main effect for A
a1.b1 a2.b1 a1.b2 a2.b2 
    3     1     2     4 
> unlist(lapply(cell_data,length)) # the cell sizes - A and B are confounded
a1.b1 a2.b1 a1.b2 a2.b2 
    5     3     5     7 
````

While `aov` showed the expected artifact of an effect for A:
````
> stats_fit <- aov(y ~ A * B, data = some_data)
> car::Anova(stats_fit,type = 3)
Anova Table (Type III tests)

Response: y
            Sum Sq Df F value    Pr(>F)    
(Intercept) 45.000  1  45.000 5.026e-06 ***
A            7.500  1   7.500 0.0145711 *  
B            2.500  1   2.500 0.1334103    
A:B         18.261  1  18.261 0.0005822 ***
Residuals   16.000 16                      
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
````

`aov_4` did not:
````
> library(afex)
> afex_fit <- aov_4(y ~ A * B + (1|id), data = some_data)
Contrasts set to contr.sum for the following variables: A, B
> afex_fit
Anova Table (Type 3 tests)

Response: y
  Effect    df  MSE         F    ges p.value
1      A 1, 16 1.00      0.00 <.0001    >.99
2      B 1, 16 1.00    4.57 *    .22     .05
3    A:B 1, 16 1.00 18.26 ***    .53   .0006
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
````

I would expect `aov_4` to "fail" in the same manner as `aov`. Could you explain where these differences stem from? (asking for myself, but also for my students).

Thanks!

**Comment by singmann** [comment]
I guess the reason for the difference is treatment versus contrast coding and the use of Type 3 tests. If you use the default coding and Type 3 tests in your example, then the results are not really sensible. 

For Type 3 tests, a type of coding where the intercept corresponds to the unweighted mean is necessary. And then, the  problem you want to show should not appear anymore, as Type 3 tests somewhat control for the difference in coding.

So without seeing that data my suggestion is to use: `afex::set_sum_contrasts()` before the `aov` call and then you should see equivalent results between this and `afex`. If not, I will need the data.

**Comment by mattansb** [comment]
`afex::set_sum_contrasts()` did exactly what you said - `aov` produced the same results as `aov_4`. (I also made the sample data available, nonetheless.)
Still not sure why differences in coding would matter when computing type III tests, but this seems to be out of scope for the `afex` package.

Thanks again!

**Comment by singmann** [comment]
This is a general feature of all regression type models with categorical covariates.
[Our chapter on mixed models](http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf) talks about this a bit in section "Parameterization of Categorical Covariates" (pp. 24). So although we talk about mixed models, it is a general issue. 

And please note that my previous response contained an error. It should be something like:

> For Type 3 tests, a type of coding where the intercept corresponds to the unweighted mean is necessary. And then, the problem you want to show should not appear anymore, as Type 3 tests somewhat control for the **difference in sample sizes, essentially by treating all groups as if they had equal sample size**.

Note again: **Using Type III test for unbalanced data without appropriate coding results in nonsensical results.**
