### ISSUE TITLE
`afex_plot` not fully compatible with glmm

### ISSUE THREAD

**Issue by mattansb** [singmann/afex#65]
When fitting a glmm model (either with `lme4::glmer` or with `afex::mixed`), I've found that I cannot use `afex_plot` to plot the following:
- Original data is not plotted (I suspect due to the link-transformed scale?)
- When trying to plot the response scale (by passing `emmeans_arg = list(type = "response")`), an error is produced.

````
> library(afex)
> library(mlmRev)
>
> gm1 <- mixed(use ~ age + I(age^2) + urban + livch + (1 | district), method = 'LRT',
+              family = binomial, data = Contraception)
>
> afex_plot(gm1,~age,emmeans_arg = list(type = "response"),data_plot = TRUE)
Aggregating data over: district
Error in FUN(X[[i]], ...) : object 'y' not found
In addition: There were 50 or more warnings (use warnings() to see the first 50)
````

I suspect that I am pushing `afex_plot` to its limit, perhaps beyond its intended use.

Thanks!

**Comment by singmann** [comment]
This should be solved in the development version: `devtools::install_github("singmann/afex@master")`

You do not even need to pass the extra `emmeans_arg` argument. The following should produce a plot:

`afex_plot(gm1, "urban", data_plot = TRUE)`

However, it still does not print the raw data in the background as the original dv is a factor.

**Comment by mattansb** [comment]
Great, thank!

I also managed to plot the data:

````
library(afex)
library(mlmRev)

Contraception <- within(Contraception,use <- as.numeric(use)-1) # for plotting the data

gm1 <- mixed(use ~ age + I(age^2) + urban + livch + (1 | district), method = 'LRT',
             family = binomial, data = Contraception)

afex_plot(gm1,~age,data_plot = TRUE)
````

**Comment by singmann** [comment]
Unfortunately this is not easily possible. This really requires thinking about and constructing the plot in a very different manner. The reason is that this requires plotting a linear slope or other function, thus completely different geoms, and the usage of `emtrends` instead of `emmeans`. So it really would be quite a different function then it is today.

I think your best bet here is to use the [`effects`](https://cran.r-project.org/package=effects) package, which was developed exactly for that (but is not so convenient for factorial designs for which `afex_plot` was developed). 

```
library(afex)
library(mlmRev)
gm1 <- mixed(use ~ age + I(age^2) + urban + livch + (1 | district), method = 'LRT',
             family = binomial, data = Contraception, set_data_arg = TRUE)
library(effects)
plot(Effect("age", gm1$full_model))
```

**Comment by mattansb** [comment]
Thanks for the suggestion!
I really like how `afex_plot` also has the original data, and it seems that `effects` is having some difficulties with this with this a glmm model (I can only guess do to the residuals being put through the link function):

````
library(afex)
library(mlmRev)
Contraception <- within(Contraception,use <- as.numeric(use)-1) # for plotting the data
gm1 <- mixed(use ~ age + I(age^2) + urban + livch + (1 | district), method = 'LRT',
             family = binomial, data = Contraception, set_data_arg = TRUE)
library(effects)
plot(Effect("age", gm1$full_model,residuals = TRUE))
````
![image](https://user-images.githubusercontent.com/35330040/51340248-11a63580-1a97-11e9-9814-de4be6c75767.png)

I guess I didn't think about the need to change geoms etc. Though I think it might still be enough to just coerce the x back to continuous via `as.numeric(as.charachter(x))` and keep the discrete geoms (doesn't look **too** bad):
````
afex_plot(gm1,~age,data_plot = TRUE, emmeans_arg = list(cov.red = FALSE))
````
![image](https://user-images.githubusercontent.com/35330040/51340037-9d6b9200-1a96-11e9-9b0f-be979cfdef19.png)


So for the time being... If I ever need a continuous x-axis, I will use with `afex_plot` with `return = "data"`, and reconstruct my plot (in a very very very roundabout way):

````
library(ggplot2)
X <- afex_plot(gm1,~age,data_plot = TRUE, emmeans_arg = list(cov.red = FALSE),return = 'data')
ggplot(mapping = aes(as.numeric(as.character(x)),y)) + 
  geom_point(data = X$data, alpha = .1) + 
  geom_ribbon(aes(ymin = lower, ymax = upper),data = X$means, color = NA, alpha = .4) + 
  geom_line(data = X$means)
````
![image](https://user-images.githubusercontent.com/35330040/51340295-2f739a80-1a97-11e9-9da7-ee38135d0594.png)
