### ISSUE TITLE
afex_plot appears to be broken

### ISSUE THREAD

**Issue by stefanradev93** [singmann/afex#72]
Dear Henrik,

today I attempted a very simple analysis:

aov_fit = aov_ez(data=data, id="id", dv="psd", between="Group", within=c("Time", "Frequency"))

afex_plot(aov_fit, x='Time', trace='Group', panel='Frequency')

which throws the following error:
Error in ref_grid(object, ...) : 
  Can't handle an object of class  “afex_aov” 
 Use help("models", package = "emmeans") for information on supported models.

I also attempted to reproduce the plots from your example here:
https://cran.r-project.org/web/packages/afex/vignettes/afex_anova_example.html

and afex_plot broke down given the same error.

Library versions:
afex version: ‘0.23.0’
emmeans version: ‘1.3.5’
ggplot2 version: ‘3.1.1’

What might be at issue here?

Regards,
Stefan

**Comment by singmann** [comment]
The following works for me without a problem (and also on CRAN, otherwise we would [see errors]()):

**Comment by singmann** [comment]
I just checked, works for me also with `emmeans` `1.3.5`. Maybe you need to reinstall the relevant packages (please note that this requires restarting R as well).
