### ISSUE TITLE
Cannot load package, possibly because of emmeans

### ISSUE THREAD

**Issue by Nico-Rojas** [singmann/afex#75]
Hi Henrik, 

When I try to load the afex library, I get the following error: 

>  library(afex)
> Error: package or namespace load failed for ‘afex’:
>  .onLoad failed in loadNamespace() for 'afex', details:
>   call: NULL
>   error: '.emm_register' is not an exported object from 'namespace:emmeans'

I checked that: 
- I have the latest version of `emmeans` and it works. 
- I have the latest version of `namespace`, nothing to update there. 
- I have the latest version of `r`, nothing to update there. 
- I did not find anyone having a similar issue here. 
- It could be the case the emmeans update from September 12th is behind this. However, I tried installing older versions of emmeans by doing things like the code below. But it did not work. 
- I also tried to installing older verision of afex by a similar procedure but I got an error saying that `afex.rdb` is corrupt

`remove.packages(package = "emmeans")`
`packageurl <- "https://cran.r-project.org/src/contrib/Archive/emmeans/emmeans_1.3.4.tar.gz"`
`install.packages(packageurl, repos=NULL, type="source")`

Many thanks.   
Nico.

**Comment by singmann** [comment]
Sorry for the slow reply, I somehow had missed this. Is this still a problem?

**Comment by Nico-Rojas** [comment]
Hi Henrik, thank you for your answer.  Yes. It still does not work.

**Comment by singmann** [comment]
This clearly is an installation problem related to `emmeans`. One obvious possibility is that you have an old version of `R`, presumably < `3.5`. So if you have old `R`, you might need to update `R`.

If this is not the case, you need to delete the involved packages (i.e., `afex` and `emmeans`) from your hard disk (location depends on OS) and reinstall everything. 

If neither of this works, the output of `sessionInfo()` after trying to load `afex` is required. But it is clearly it is a package installation problem related to `emmeans`.
