### ISSUE TITLE
Why aov_ez default output GG corrected results?

### ISSUE THREAD

**Issue by Youguang** [singmann/afex#76]
Why aov_ez default output GG corrected results even while Mauchly Tests for Sphericity is not significant? Is that appropriate? 

Is there an easy manner to extract the Mauchly Tests p-value from afex_aov objects? I want to set correction method based on that. Or is it possible to provided an `Auto` correct option besides `GG` and `HF` based this:

![image](https://user-images.githubusercontent.com/7878120/65863151-2c5cd800-e3a2-11e9-8150-eae132a5d758.png)

**Comment by singmann** [comment]
I think it is appropriate, that is why it is implemented this way. To me this is the more conservative choice.

Please see here for my reasons: https://afex.singmann.science/forums/topic/default-sphericity-correction-method-gg

Also, it should now be easy to get the Mauchly test via `summary(model)`.

**Comment by Youguang** [comment]
Thanks for your reply.
