### ISSUE TITLE
results of lmer_alt depend on contrast-type

### ISSUE THREAD

**Issue by mattansb** [singmann/afex#77]
When using `lmer_alt` for the ability to use `||` with factors, the results vary depending the type of factor contrasts used:
``` r
library(afex)

set_treatment_contrasts()
#> setting contr.treatment globally: options(contrasts=c('contr.treatment', 'contr.poly'))

fit_t <- lmer_alt(value ~ phase + (phase || id),
                  data = obk.long,
                  check_contrasts = FALSE, expand_re = TRUE)

set_effects_contrasts()
#> setting contr.sum globally: options(contrasts=c('contr.sum', 'contr.poly'))

fit_e <- lmer_alt(value ~ phase + (phase || id),
                  data = obk.long,
                  check_contrasts = FALSE, expand_re = TRUE)


anova(fit_t)
#> Type III Analysis of Variance Table with Satterthwaite's method
#>       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
#> phase 46.155  23.078     2 16.765  14.036 0.0002623 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
anova(fit_e)
#> Type III Analysis of Variance Table with Satterthwaite's method
#>       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
#> phase  45.04   22.52     2 21.527  13.856 0.0001356 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

I'm not sure if this is an intended behavior, but I didn't expect this to happen*. Should this happen? If so, which option is the preferred one (or what is the underlying difference)?

(* in the above example the results only vary slightly, but I came across this in real world data where the differences was very big - like conclusion changing big, but unfortunately I cannot share the data as it is not mine)

**Comment by singmann** [comment]
Sorry for taking such a long time to get to this. This is indeed surprising and it took me a bit of thinking to understand what is hapenning here. There are two different issues I think at play here:

1. The main difference between the models is the specification of the random-effects terms using either treatment or sum-to-zero contrasts. This affects how hierarchical-shrinkage affects the model predictions. More specifically, one somewhat subtle difference between ordinary linear models and linear mixed models is that for the former the observed and estimated marginal means coincide. For the latter, this is not the case as hierarchical shrinkage is applied to the individual deviations which then affects the model predictions. And the models differ in whether the shrinkage is applied to the sum-to-zero coded deviations or the treament coded deviations. This then affects how well the model can describe the data.
2. In addition to this, there seems to be an issue in how the Satterthwaite deals with the differences mentioned above. This appears to be a problem specific to the Satterthewaite method.

The first thing to note is that the issue shown here does generally not depend on the coding of the fixed-effects, but the coding of the random-effects. We can show this by creating the two-different coding schemes by-hand using `model.matrix` and show that this changes the results for the random-effects estimates, but not the coding of the fixed effects:

```r
library(afex)
data(obk.long)

set_sum_contrasts()

mm_sum <- model.matrix(~ phase, obk.long)
head(mm_sum)
#   (Intercept) phase1 phase2
# 1           1     -1     -1
# 2           1     -1     -1
# 3           1     -1     -1
# 4           1     -1     -1
# 5           1     -1     -1
# 6           1      0      1

set_treatment_contrasts()
mm_treat <- model.matrix(~ phase, obk.long)
head(mm_treat)
#   (Intercept) phasepost phasepre
# 1           1         0        1
# 2           1         0        1
# 3           1         0        1
# 4           1         0        1
# 5           1         0        1
# 6           1         1        0

library("tidyverse")

obk2 <- bind_cols(
  obk.long,
  as_tibble(mm_sum, .name_repair = "universal"),
  as_tibble(mm_treat, .name_repair = "universal")[,-1]
) %>% 
  as_tibble()
obk2
# # A tibble: 240 x 12
#    id    treatment gender   age phase hour  value .Intercept. phase1 phase2 phasepost phasepre
#    <fct> <fct>     <fct>  <dbl> <fct> <fct> <dbl>       <dbl>  <dbl>  <dbl>     <dbl>    <dbl>
#  1 1     control   M      -4.75 pre   1         1           1     -1     -1         0        1
#  2 1     control   M      -4.75 pre   2         2           1     -1     -1         0        1
#  3 1     control   M      -4.75 pre   3         4           1     -1     -1         0        1
#  4 1     control   M      -4.75 pre   4         2           1     -1     -1         0        1
#  5 1     control   M      -4.75 pre   5         1           1     -1     -1         0        1
#  6 1     control   M      -4.75 post  1         3           1      0      1         1        0
#  7 1     control   M      -4.75 post  2         2           1      0      1         1        0
#  8 1     control   M      -4.75 post  3         5           1      0      1         1        0
#  9 1     control   M      -4.75 post  4         3           1      0      1         1        0
# 10 1     control   M      -4.75 post  5         2           1      0      1         1        0
# # ... with 230 more rows

m1 <- lmer(value ~ phase + (.Intercept. + phase1 + phase2 || id), obk2)
m2 <- lmer(value ~ phase + (.Intercept. + phasepost + phasepre || id), obk2)


set_sum_contrasts()
m3 <- lmer(value ~ phase + (.Intercept. + phase1 + phase2 || id), obk2)
m4 <- lmer(value ~ phase + (.Intercept. + phasepost + phasepre || id), obk2)

###

summary(m1)$varcor
summary(m3)$varcor
 # Groups   Name        Std.Dev.
 # id       (Intercept) 1.10309 
 # id.1     .Intercept. 1.16486 
 # id.2     phase1      0.55905 
 # id.3     phase2      0.67194 
 # Residual             1.27485 

summary(m2)$varcor
summary(m4)$varcor
 # Groups   Name        Std.Dev.
 # id       (Intercept) 1.24748 
 # id.1     .Intercept. 1.21909 
 # id.2     phasepost   0.64265 
 # id.3     phasepre    1.33999 
 # Residual             1.28230 
```

Here, `m1` and `m3` have the same coding of the random-effects (sum-contrasts), but differ in the coding of the fixed effects, and also produce the same results. Importantly, the residual SD is the same. Likewise, `m2` and `m4` both use treatment contrasts for the random-effects and show the same results. 

This equivalence of results based on the random-effects also applies to the inferential statistics as long as the Satterthwaite is not used:

```
lme4:::anova.merMod(m1)
lme4:::anova.merMod(m3)
# Analysis of Variance Table
#       Df Sum Sq Mean Sq F value
# phase  2 45.032  22.516  13.854

lme4:::anova.merMod(m2)
lme4:::anova.merMod(m4)
# Analysis of Variance Table
#       Df Sum Sq Mean Sq F value
# phase  2  46.16   23.08  14.036

anova(m1, ddf = "Kenward-Roger")
anova(m3, ddf = "Kenward-Roger")
# Type III Analysis of Variance Table with Kenward-Roger's method
#       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
# phase 45.032  22.516     2 19.455  13.377 0.0002215 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

anova(m2, ddf = "Kenward-Roger")
anova(m4, ddf = "Kenward-Roger")
# Type III Analysis of Variance Table with Kenward-Roger's method
#       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
# phase  46.16   23.08     2 20.076  13.567 0.0001872 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

As soon as we use the Satterthwaite method, the results suddenly differ in unexpected ways that I cannot fully explain. It may be something to discuss with the maintainer of `lmerTest`, who has implemented this method.

```
anova(m1)
# Type III Analysis of Variance Table with Satterthwaite's method
#       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
# phase 45.032  22.516     2 31.741  13.854 4.731e-05 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

anova(m2)
# Type III Analysis of Variance Table with Satterthwaite's method
#       Sum Sq Mean Sq NumDF  DenDF F value   Pr(>F)    
# phase  46.16   23.08     2 16.769  14.036 0.000262 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

anova(m3)
# Type III Analysis of Variance Table with Satterthwaite's method
#       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
# phase 45.032  22.516     2 21.519  13.854 0.0001359 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

anova(m4)
# Type III Analysis of Variance Table with Satterthwaite's method
#       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
# phase  46.16   23.08     2 21.463  14.036 0.0001265 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

So my take away is that if it matters for the predictions how the random-effects are coded, Satterthwaite seems to be the wrong method. Please also note that the code above does not actually use `afex` (but it essentially recreates what `expand_re` does).

**Comment by mattansb** [comment]
Henrik, thanks for this very detailed response! This was really quite eye opening...

I hope you don't mind I have some minor follow-up questions (obviously take your time in replying, if at all - as these aren't really `afex` related questions, but general HLM questions...).

1. If I understand correctly, Satterthwaite's method should not be used for getting DoFs here (at all?).

2. But would you suggest I do with the coding of the random-effects?
For my case-usage, I generally am not interested in the model's parameters _per se_, but I use `emmeans` to get estimates and conduct follow-up analyses. What would you suggest for such a case - is it better the random-effects' coding match the coding of the fixed effects? or would you suggest always using a specific one (which)?

Thanks again!

**Comment by singmann** [comment]
In this particular case the Satterthwaite method does appear a bit wonky. So I would not use it here, but Kenward-Roger.

The question which coding to use is difficult. Either coding scheme makes interpretation a bit difficult if you have interaction as part of the random-slopes. However, usually the impact of this should be low. So if the coding of the random-effects parameters matters for the results, I would be very careful. The results are then probably not very strong.

**Comment by mattansb** [comment]
Thanks Henrik!
