### ISSUE TITLE
nice.anova() printing of p values

### ISSUE THREAD

**Issue by mariusbarth** [singmann/afex#81]
Hi Henrik,

we started teaching R to our students here in Cologne, and we use `afex` to teach ANOVA and ANCOVA. (So kudos for creating this versatile and user friendly package!) However, there is one thing in the ANOVA output generated by `nice.anova()` that led to a lot of confusion this semester:

Currently, the number of printed digits for *p* values depends on the *p* value itself, i.e. large *p* values are rounded to two digits, while smaller *p* values are rounded to three (for *p* < .01) or even four digits (for *p* < .001). I dug into the code and found that you put some effort into implementing this behavior, and so I believe you had some good reasons for doing so. However, I would like to convince you that it would be better to always round to three digits for the following reasons:

1. The APA publication manual states: "When reporting *p* values, report exact *p* values (e.g., *p* = .031) to two or three decimal places. However, report *p* values less than .001 as *p* < .001. So I believe always rounding to three digits (with *p* < .001 as an edge case) is consistent, while *p* < .0001 (four decimal places) does not adhere to APA guidelines. Moreover, currently only values below .01 are reported with three decimal digits, so even the *p* value from the text excerpt would result in *p* = .03 instead of *p* = .031.
2. As far as I understand, the exact *p* value in a single study is not informative -- instead, exact *p* values are only really useful in meta analysis, for instance *p*-curve analysis. However, for such purposes, values above or below a specific threshold are important, and therefore I believe encouraging users to always report *p* values up to three decimal places is a good idea.

I would be happy to create a PR if I could convince you.

Best,
Marius

**Comment by singmann** [comment]
I honestly don't particularly like rounding to 3 decimal digits for values above .01, even if these are the APA guidelines. The good reason (IMHO) it is implemented differently is simply that I like how it now looks. So I would be unwilling to change the default behaviour.

Having said that, I can imagine accepting a pull request that adds an argument to `nice` which gets its default from `afex_options()` which specifies how p-values are rounded. For example, we could call this argument `round_p` with default `afex_options("round_p")` which is set to `round_ps`. 

For ease of use I would suggest `round_p` accepts a function that rounds a p-value or an integer. The latter specifies the number of digits to which p-values should be rounded. The function simply can be any function that accepts a numeric vector and returns a character vector.

So to get APA standard, users would just have to call `afex_options("round_p" = 3)` once per session.

Does this sound like something that would be of interest to you? In that case, the pull request should add this to all three `nice` methods ideally.

**Comment by mariusbarth** [comment]
Hi Henrik,

thanks for your quick reply! I think it is a nice idea to allow users to further customize the output. However, in my case (with students being a bit helpless getting the "right" numbers out of the output), I am hesitant to put such an extra burden (setting an extra option) on students -- one reason being teaching time that would be lost to some rather "technical" issue, the other that I want to avoid the impression that it is hacky or difficult to use R when you're using it as a newbie. Maybe I will just go for not asking for *p* values in my assignments. :P 

Best, Marius

**Comment by singmann** [comment]
One of the core ideas behind the development of `afex` is that it should be as user friendly as possible. That means that for a total `R` newbie that uses `afex`, the probability should be high that they get the output they understand and can work with. So contrary to what I have said above, if my way of rounding p-values really is not the way that achieves that, I am in principle willing to change the default behaviour. 

However, I am not sure that an argument that is largely based on the APA manual alone is enough to convince me that it does so. From your description it seems that the main problem is that students expect something that follows APA guidelines to the letter and the current default behaviour is slightly not in line with that. But on the other hand, `afex` has many users that are not necessarily psychologists so following this one set of guidelines seems a bit overzealous (although of course, APA guidelines play a big role in the development). 

So I guess the question for me boils down to this: Is it really not okay to round p-values above .01 to 2 decimal digits and below to 3 digits or even 4 digits (if below < .001). Or asked differently, does it make statistical sense to distinguish say .028 from .032 or is it fine if these are just reported as .03 when at the same time we would also report .003? I am not yet convinced enough by the meta-analysis or p-curve argument.

If I am wrong in my, admittedly, sloppiness I am of course willing to change my mind. Otherwise, a flag or some call to a global options that strictly enforces APA guidelines (say `afex_options("APA" = TRUE)`) would still look like the better option to me.

**Comment by mariusbarth** [comment]
Hm, after thinking about it, I believe there is also one good statistical argument for printing three decimal digits:

- For instance, consider you set your alpha error probability to .05 and your nonrounded *p* is either *p* = .0456789 (significant) or *p* = .0548247 (nonsignificant). Still, both *p* values would result in a rounded *p* = .05.
- For alpha = .01, *p* values above the threshold might be confusing: For instance, a *p* = .0147 would be rounded to .01, which, if it was not a rounded value, would be a significant value.

Put in another way, if a user only interprets *p* values and ignores the stars in the output, with rounding to two decimal places, the resulting alpha levels  would be .055 for nominal alpha = .05 and .015 for nominal alpha = .01. Rounding to three decimal places does not resolve the general problem, but resulting alpha would be .0505 and .0105, respectively.

I think many users will note the inconsistency between stars and *p* values resulting in such situations and will double-check, but still these inconsistent cases will need some deliberation and this double-checking by the user. Rounding to three decimal places would reduce the number of cases in which such deliberation is necessary by a factor of 10.

**Comment by singmann** [comment]
Hmm, I also do not find this extremely convincing. The output shows the stars so people would really have to ignore them actively. I mean, it is not the worst argument, but still more of an opinion than some hard evidence why the current default is not correct. 

Are you aware of any literature that discusses the rounding of p-values other than the APA manual. I feel this would really go a long way.

**Comment by mariusbarth** [comment]
There is this finding that *p* values just above .05 are frequently rounded to .05 and then reported as being significant: https://doi.org/10.1080/17470218.2013.863371
While this really might be based on bad intent and actively ignoring the stars, it could also be the result of gladly reading .05, thinking it is significant, and not remembering to actively search for contradictory information (i.e., the absence of a star). You're right, maybe it's good to give it some further thought before rushing into changing the code.

**Comment by singmann** [comment]
I have to admit I am getting more and more warmed up to the idea of rounding to three decimal digits by default. However, I will be not available next week. So if you still find more relevant literature, let me know.

**Comment by mariusbarth** [comment]
I think this one might be relevant, especially pp. 671-672:
Bakker, M. & Wicherts, J.M. Behav Res (2011) 43: 666. https://doi.org/10.3758/s13428-011-0089-5

**Comment by singmann** [comment]
Should be addressed now. See the following code, which also shows how to reset the old behaviour:

```r
library("afex")
data(obk.long, package = "afex")

# estimate mixed ANOVA on the full design:
aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
        data = obk.long, observed = "gender")
# Contrasts set to contr.sum for the following variables: treatment, gender
# Anova Table (Type 3 tests)
# 
# Response: value
#                         Effect          df   MSE         F  ges p.value
# 1                    treatment       2, 10 22.81    3.94 +  .20     .05
# 2                       gender       1, 10 22.81    3.66 +  .11     .08
# 3             treatment:gender       2, 10 22.81      2.86  .18     .10
# 4                        phase 1.60, 15.99  5.02 16.13 ***  .15   .0003
# 5              treatment:phase 3.20, 15.99  5.02    4.85 *  .10     .01
# 6                 gender:phase 1.60, 15.99  5.02      0.28 .003     .71
# 7       treatment:gender:phase 3.20, 15.99  5.02      0.64  .01     .61
# 8                         hour 1.84, 18.41  3.39 16.69 ***  .13  <.0001
# 9               treatment:hour 3.68, 18.41  3.39      0.09 .002     .98
# 10                 gender:hour 1.84, 18.41  3.39      0.45 .004     .63
# 11       treatment:gender:hour 3.68, 18.41  3.39      0.62  .01     .64
# 12                  phase:hour 3.60, 35.96  2.67      1.18  .02     .33
# 13        treatment:phase:hour 7.19, 35.96  2.67      0.35 .009     .93
# 14           gender:phase:hour 3.60, 35.96  2.67      0.93  .01     .45
# 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74  .02     .65
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
# 
# Sphericity correction method: GG 

afex_options(round_ps = round_ps)
aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
        data = obk.long, observed = "gender")
# Contrasts set to contr.sum for the following variables: treatment, gender
# Anova Table (Type 3 tests)
# 
# Response: value
#                         Effect          df   MSE         F  ges p.value
# 1                    treatment       2, 10 22.81    3.94 +  .20     .05
# 2                       gender       1, 10 22.81    3.66 +  .11     .08
# 3             treatment:gender       2, 10 22.81      2.86  .18     .10
# 4                        phase 1.60, 15.99  5.02 16.13 ***  .15   .0003
# 5              treatment:phase 3.20, 15.99  5.02    4.85 *  .10     .01
# 6                 gender:phase 1.60, 15.99  5.02      0.28 .003     .71
# 7       treatment:gender:phase 3.20, 15.99  5.02      0.64  .01     .61
# 8                         hour 1.84, 18.41  3.39 16.69 ***  .13  <.0001
# 9               treatment:hour 3.68, 18.41  3.39      0.09 .002     .98
# 10                 gender:hour 1.84, 18.41  3.39      0.45 .004     .63
# 11       treatment:gender:hour 3.68, 18.41  3.39      0.62  .01     .64
# 12                  phase:hour 3.60, 35.96  2.67      1.18  .02     .33
# 13        treatment:phase:hour 7.19, 35.96  2.67      0.35 .009     .93
# 14           gender:phase:hour 3.60, 35.96  2.67      0.93  .01     .45
# 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74  .02     .65
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
# 
# Sphericity correction method: GG 
```

**Comment by singmann** [comment]
Should be addressed now and can be controlled via global options.

```r
library("afex")
data(obk.long, package = "afex")

# estimate mixed ANOVA on the full design:
aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
        data = obk.long, observed = "gender")
# Contrasts set to contr.sum for the following variables: treatment, gender
# Anova Table (Type 3 tests)
# 
# Response: value
#                         Effect          df   MSE         F  ges p.value
# 1                    treatment       2, 10 22.81    3.94 + .198    .055
# 2                       gender       1, 10 22.81    3.66 + .115    .085
# 3             treatment:gender       2, 10 22.81      2.86 .179    .104
# 4                        phase 1.60, 15.99  5.02 16.13 *** .151   <.001
# 5              treatment:phase 3.20, 15.99  5.02    4.85 * .097    .013
# 6                 gender:phase 1.60, 15.99  5.02      0.28 .003    .709
# 7       treatment:gender:phase 3.20, 15.99  5.02      0.64 .014    .612
# 8                         hour 1.84, 18.41  3.39 16.69 *** .125   <.001
# 9               treatment:hour 3.68, 18.41  3.39      0.09 .002    .979
# 10                 gender:hour 1.84, 18.41  3.39      0.45 .004    .628
# 11       treatment:gender:hour 3.68, 18.41  3.39      0.62 .011    .641
# 12                  phase:hour 3.60, 35.96  2.67      1.18 .015    .335
# 13        treatment:phase:hour 7.19, 35.96  2.67      0.35 .009    .930
# 14           gender:phase:hour 3.60, 35.96  2.67      0.93 .012    .449
# 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74 .019    .646
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
# 
# Sphericity correction method: GG 

afex_options(round_ps = round_ps)
aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
        data = obk.long, observed = "gender")
# Contrasts set to contr.sum for the following variables: treatment, gender
# Anova Table (Type 3 tests)
# 
# Response: value
#                         Effect          df   MSE         F  ges p.value
# 1                    treatment       2, 10 22.81    3.94 +  .20     .05
# 2                       gender       1, 10 22.81    3.66 +  .11     .08
# 3             treatment:gender       2, 10 22.81      2.86  .18     .10
# 4                        phase 1.60, 15.99  5.02 16.13 ***  .15   .0003
# 5              treatment:phase 3.20, 15.99  5.02    4.85 *  .10     .01
# 6                 gender:phase 1.60, 15.99  5.02      0.28 .003     .71
# 7       treatment:gender:phase 3.20, 15.99  5.02      0.64  .01     .61
# 8                         hour 1.84, 18.41  3.39 16.69 ***  .13  <.0001
# 9               treatment:hour 3.68, 18.41  3.39      0.09 .002     .98
# 10                 gender:hour 1.84, 18.41  3.39      0.45 .004     .63
# 11       treatment:gender:hour 3.68, 18.41  3.39      0.62  .01     .64
# 12                  phase:hour 3.60, 35.96  2.67      1.18  .02     .33
# 13        treatment:phase:hour 7.19, 35.96  2.67      0.35 .009     .93
# 14           gender:phase:hour 3.60, 35.96  2.67      0.93  .01     .45
# 15 treatment:gender:phase:hour 7.19, 35.96  2.67      0.74  .02     .65
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
# 
# Sphericity correction method: GG 
```

Should also work if `afex` is not attached.

**Comment by singmann** [comment]
New `afex` version with this feature is on its way to CRAN.

**Comment by singmann** [comment]
And it has finally arrived on CRAN.
