### ISSUE TITLE
Thanks for the new afex Tutorial - reporting some typos I found.

### ISSUE THREAD

**Issue by m-Py** [singmann/afex#82]
Hello Henrik,

Thanks for your tutorials on the afex package, they are really helpful! 

Just dropping by to inform you about some typos I found in your new tutorial (http://singmann.github.io/afex/doc/afex_analysing_accuracy_data.html). Not sure if this is the best place to report, but I kinda didn't want to post them under your twitter announcement.

**Section Mixed Model Analysis**

- 2nd parapgraph: "th ecorrect family" -> "the correct family"
- 3rd paragraph: "tetsing" -> "testing"
- 3rd paragraph: "goruping" -> "grouping"; 
- 3rd paragraph: "no tnecessary" -> "not necessary" 
- 4th: "setup such models" -> "set up such models"
- 4th: "then the first way" -> "than the first way"

**Section Analysis of Two Studies with GLMM**

- 4th: "data froM Experiment 1" -> "data from Experiment 1"

I will update if I should find any others.

Cheers, 

Martin

**Comment by singmann** [comment]
Thanks, fixed. I also run the `RStudio` spell checker and found quite a few more typos. New version should be up now. Please post more typos if you find them.
