### ISSUE TITLE
Observed and df correction attributes for nice data.frames

### ISSUE THREAD

**Issue by crsh** [singmann/afex#9]
Hi Henrik,

I'm currently working on refining the support of `afex_aov` objects in my package `papaja`. It's already a pretty seamless integration, however, there are some redundancies for options that users set when calling `aov_car`. Some options have to be set again in `papaja` functions because there is no way of knowing the original parameters. As far as I can tell, it is, e.g., impossible to deduce how df were corrected in within-subject designs or which factors were observed.

What do you think about adding these parameters as attributes to the `anova_table` as I have done in my previous pull request with the `p.adjust.method`? I'd be happy to do this myself but I wanted to check with you first before getting started.

**Comment by singmann** [comment]
Sounds like a very reasonable suggestion. Thanks for taking this on. 
And sorry for the long delay, I was at the Psychonomic society meeting.
