### ISSUE TITLE
Using other observations of a participant with a single NA in ANOVA

### ISSUE THREAD

**Issue by OmidGhasemi21** [singmann/afex#90]
Hi Henrik,

In my dataset, one of the participants has a single NA. The model that I run is excluding that participant from the analysis. I set `na.rm=TRUE`, but it does not work.

```
m1 <-aov_car (accuracy ~ group * time +
                                Error(tester_key/time), data = my_data, factorize = F, na.rm=T)


--------    Output   ---------
Missing values for following ID(s):
subj_12
Removing those cases from the analysis. 
```

How can I set `afex` to use other observations of that participant and not to exclude it?

Thank you.

**Comment by singmann** [comment]
That is simple, you cannot. Repeated measures ANOVA can only handle complete data. 

If you want to use partial data, mixed models can do so (e.g., `afex::mixed`). But of course these models are also somewhat more difficult to setup and require more care. If of interest to you I recommend: http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf
