### ISSUE TITLE
Any update mechanism with afex?

### ISSUE THREAD

**Issue by afni-gangc** [singmann/afex#91]
Suppose I have a linear model that is formulated as

```
aov_car(y ~ treatment * gender + age + Error(id/(phase*hour)), 
          data = obk.long, observed = c("gender", "age"), factorize = FALSE)
```

I need to repeat the computation many times (e.g., 5000) for the same explanatory variables (e.g., treatment, gender, etc.) but with different `y`. I would like to save the overhead setup time, so is there a mechanism with afex to set up the model and the common matrix operations, and then just directly feed them into aov_car and apply to all the models with different `y`? Maybe something similar to `update` in the R package `nlme`.

**Comment by singmann** [comment]
There is no `update` function or something similar. However, the one thing you can do that speeds up the computation is disabling computation of the `aov` model by setting `include_aov = FALSE` or globally for the session: `afex_options("include_aov" = FALSE)`.

You could also use one of the alternative return values specified through the `return` argument for some small speed ups, but this depends on what you need.

``` r
library("afex")
library("microbenchmark")
set_sum_contrasts()
#> setting contr.sum globally: options(contrasts=c('contr.sum', 'contr.poly'))

microbenchmark(
  aov_car(value ~ treatment * gender + age + Error(id/(phase*hour)), 
          data = obk.long, observed = c("gender", "age"), factorize = FALSE),
  aov_car(value ~ treatment * gender + age + Error(id/(phase*hour)), 
          data = obk.long, observed = c("gender", "age"), factorize = FALSE, 
          include_aov = FALSE), 
  aov_car(value ~ treatment * gender + age + Error(id/(phase*hour)), 
          data = obk.long, observed = c("gender", "age"), factorize = FALSE, 
          include_aov = FALSE, return = "Anova"),
  aov_car(value ~ treatment * gender + age + Error(id/(phase*hour)), 
          data = obk.long, observed = c("gender", "age"), factorize = FALSE, 
          include_aov = FALSE, return = "univariate")
)
#> Unit: milliseconds
#>                                                                                                                                                                                           expr
#>                                                   aov_car(value ~ treatment * gender + age + Error(id/(phase *      hour)), data = obk.long, observed = c("gender", "age"), factorize = FALSE)
#>                         aov_car(value ~ treatment * gender + age + Error(id/(phase *      hour)), data = obk.long, observed = c("gender", "age"), factorize = FALSE,      include_aov = FALSE)
#>       aov_car(value ~ treatment * gender + age + Error(id/(phase *      hour)), data = obk.long, observed = c("gender", "age"), factorize = FALSE,      include_aov = FALSE, return = "Anova")
#>  aov_car(value ~ treatment * gender + age + Error(id/(phase *      hour)), data = obk.long, observed = c("gender", "age"), factorize = FALSE,      include_aov = FALSE, return = "univariate")
#>      min       lq     mean   median       uq      max neval cld
#>  77.4723 82.79065 89.88740 85.79705 91.03120 189.0863   100   c
#>  57.6817 62.76175 68.54990 65.61500 70.56085 107.8882   100  b 
#>  50.1575 53.72745 61.53675 56.36505 60.36030 209.4513   100 a  
#>  55.8667 60.31920 66.50085 62.83910 67.96705 102.7924   100 ab
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I guess it is possible to speed up things more by running `update` for example only on the `lm` slot of the `afex_aov` object, but this will not be convenient. Also, it really depends on what you want to do with the result.

**Comment by afni-gangc** [comment]
Thanks a lot for the quick help, Henrik!

For each iteration, I need to get the output from aov_car and then perform some post hoc analyses using the function `testInteraction()` from the `phia` package. So, does it mean there is not much overhead time I could save in this case?

**Comment by singmann** [comment]
If I remember correctly, `testInteraction()` only requires the `Anova` object, so you could try it out with `include_aov = FALSE, return = "Anova"`. It should be a bit faster. 
And `include_aov = FALSE` can be dramatically faster if you have large data sets and both between and within factors.
