### ISSUE TITLE
plotting raw data points for a model with two random intercepts

### ISSUE THREAD

**Issue by OmidGhasemi21** [singmann/afex#95]
Hi Henrik. I am running two models, one with by-participant random intercept and one with by-participant and by-content random intercepts.

`m1 <- mixed(liking_rating ~ cog_ability*logic*belief*problem_type + ((logic+belief+problem_type)^2||participant)+
                      (logic+belief+cog_ability||content) ,liking1_df, method = "S", 
                    control = lmerControl(optimizer="bobyqa",optCtrl = list(maxfun = 1e6)), expand_re = TRUE)`

`m2 <- mixed(liking_rating ~ cog_ability*logic*belief*problem_type + ((logic+belief+problem_type)^2||participant),
                     liking1_df, method = "S", 
                    control = lmerControl(optimizer="bobyqa",optCtrl = list(maxfun = 1e6)), expand_re = TRUE)`

For the model with 1 random intercept, raw data points look fine. However, for the model with both participant and content random intercept, data points were evenly spread across the plot.

![c](https://user-images.githubusercontent.com/45413424/91777732-0126dc80-ec34-11ea-875f-9e22783681f6.png)

Can I show the data as it appears in the right figure for a model with two intercepts?

Thank you.

**Comment by singmann** [comment]
The `id` argument of `afex_plot` allows to control this, see: https://cran.r-project.org/web/packages/afex/vignettes/afex_plot_introduction.html#which-data-to-plot-in-the-background

In your case you probably want `id = "participant"` in both cases.
