### ISSUE TITLE
Getting variance for the effect instead of each level of the effect? 

### ISSUE THREAD

**Issue by xinlab** [singmann/afex#99]
I ran a linear mixed model and the random structure of the model looks weird. Instead of listing main effects and interactions for each random intercept, I got the variance for each level of each effect.

```
model1 <- mixed(logrt ~ langdir*session + 
                            (langdir*session||subj_ID),
                          german_rt_data, method = "S", expand_re = T)

summary(model1)


#Random effects:
 #98 Groups     Name                     Variance       Std.Dev.  
 #subj_ID    (Intercept)              0.016764977347 0.12947964
 #subj_ID.1  re1.langdir1             0.000000000000 0.00000000
 #subj_ID.2  re1.langdir2             0.000081143705 0.00900798
 #subj_ID.3  re1.langdir3             0.000054922027 0.00741094
 #subj_ID.4  re1.session1             0.002727354100 0.05222408
 #subj_ID.5  re1.session2             0.002045463724 0.04522680
 #subj_ID.6  re1.session3             0.002167992338 0.04656170
 #subj_ID.7  re1.langdir1_by_session1 0.000105965620 0.01029396
 #subj_ID.8  re1.langdir2_by_session1 0.000009445865 0.00307341
 #subj_ID.9  re1.langdir3_by_session1 0.000000002544 0.00005044
 #subj_ID.10 re1.langdir1_by_session2 0.000120103117 0.01095916
 #subj_ID.11 re1.langdir2_by_session2 0.000000000000 0.00000000
 #subj_ID.12 re1.langdir3_by_session2 0.000000044020 0.00020981
 #subj_ID.13 re1.langdir1_by_session3 0.000000293809 0.00054204
 #subj_ID.14 re1.langdir2_by_session3 0.000000000000 0.00000000
 #subj_ID.15 re1.langdir3_by_session3 0.000000000000 0.00000000
 #Residual                            0.027939054952 0.16714980
#Number of obs: 4858, groups:  subj_ID, 8
```
Is there any way to get variance in the following format?

```
#98 Groups     Name                             Variance       Std.Dev.  
 #subj_ID    (Intercept)                          0.016764977347 0.12947964
 #subj_ID.1  re1.langdir                         0.000000000000 0.00000000
 #subj_ID.2  re1.sesion                         0.000081143705 0.00900798
 #subj_ID.2  re1.sesion:langdir             0.000081143705 0.00900798
```
Thanks.

**Comment by singmann** [comment]
No, that is not possible (and cannot be). If you have a factor with `k` levels, it needs to be represented by `k - 1` contrast variables. Consequently, you also get variance estimates for these contrast variables.

Please also note that I am pretty sure you do not get variance estimates "for each level of each effect", but for one level less. Specifically, I assume both `langdir` and `session` have 4 levels, but you only get three variance estimates for each factor. As a consequence, there is no 1-to-1 mapping of variances to factor levels. So you cannot even interpret these estimates directly.

It is just a consequence of how regression models with factors are parameterised so there is nothing that can be done.

**Comment by xinlab** [comment]
Hi Henrik,

Thank you for your clarification. The reason that I thought I can get estimates for each effect (instead of n-1 levels of each effect) was that, in your tutorial, you got such results for your model:

```

m4s <- mixed(log_rt ~ task*stimulus*density*frequency + 
               (stimulus*density*frequency||id)+
               (task||item), fhch, method = "S", 
             control = lmerControl(optCtrl = list(maxfun = 1e6)), expand_re = TRUE)

##  Groups   Name                                    Std.Dev. 
##  item     re2.task1                               0.0568715
##  item.1   (Intercept)                             0.0537587
##  id       re1.stimulus1_by_density1_by_frequency1 0.0077923
##  id.1     re1.density1_by_frequency1              0.0000000
##  id.2     re1.stimulus1_by_frequency1             0.0000000
##  id.3     re1.stimulus1_by_density1               0.0000000
##  id.4     re1.frequency1                          0.0179993
##  id.5     re1.density1                            0.0000000
##  id.6     re1.stimulus1                           0.0445333
##  id.7     (Intercept)                             0.1936292
##  Residual                                         0.3001905
```
Moreover, if it is not possible to get such results, then the random-effect structure simplification is getting more difficult. How we can decide one factor should be removed when there are multiple variance measures for its levels?

Thank you.

**Comment by singmann** [comment]
In the example case you also get effects for `n-1` levels, but all factors have only two levels so only one contrast variable.

It is true that existing implementation makes it more difficult to decide which random-effect factor to remove, but there are still some reasonable steps: You have to start removing with the highest order effect (i.e., you cannot remove a main effect if the interaction is still present). So in your case, you have to start removing the interaction term. Then, if it still shows problem, remove the term that has a variance component that has a 0 variance parameter (i.e., `langdir` in your case).
